-- GENERATED by scripts/generate-db-baseline.ts — do not edit by hand.
-- Fresh-DB baseline: the schema every migration up to v54 (chat_source_control_options)
-- produces. migrateDB applies it to an EMPTY database and stamps v1..v54;
-- existing databases keep the historic path. Regenerate with `pnpm db:baseline`.

CREATE TABLE sessions (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      status TEXT NOT NULL DEFAULT 'created',
      model TEXT,
      repo_url TEXT,
      repo_branch TEXT,
      requires_codebase INTEGER NOT NULL DEFAULT 0,
      workspace_path TEXT,
      tags TEXT DEFAULT '[]',
      triggered_by TEXT,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      started_at INTEGER,
      completed_at INTEGER
    , conversation_id TEXT, owner_type TEXT, owner_id TEXT, closed_at INTEGER, provider_session_id TEXT);

CREATE TABLE workflows (
      id TEXT PRIMARY KEY,
      session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
      template_id TEXT NOT NULL,
      name TEXT NOT NULL,
      "order" INTEGER NOT NULL,
      status TEXT NOT NULL DEFAULT 'pending',
      conversation_id TEXT,
      variables TEXT DEFAULT '{}',
      hook_overrides TEXT DEFAULT '{}',
      copilot_config_overrides TEXT,
      current_step INTEGER DEFAULT 0,
      total_steps INTEGER DEFAULT 0,
      error TEXT,
      started_at INTEGER,
      completed_at INTEGER,
      created_at INTEGER NOT NULL
    , harness_config_overrides TEXT);

CREATE TABLE events (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      sequence_id INTEGER NOT NULL,
      kind TEXT NOT NULL,
      data TEXT NOT NULL,
      timestamp INTEGER NOT NULL
    , workflow_run_id TEXT, stage_run_id TEXT);

CREATE TABLE event_sequences (
      session_id TEXT PRIMARY KEY,
      next_sequence INTEGER NOT NULL DEFAULT 1
    );

CREATE TABLE chat_messages (
      id TEXT PRIMARY KEY,
      session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
      role TEXT NOT NULL,
      content TEXT NOT NULL,
      attachments TEXT,
      tool_name TEXT,
      tool_args TEXT,
      tool_result TEXT,
      workflow_id TEXT REFERENCES workflows(id),
      timestamp INTEGER NOT NULL
    , metadata TEXT, chat_id TEXT, agent_ref TEXT, agent_version INTEGER);

CREATE TABLE artifacts (
      id TEXT PRIMARY KEY,
      session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
      workflow_id TEXT REFERENCES workflows(id),
      name TEXT NOT NULL,
      path TEXT NOT NULL,
      mime_type TEXT,
      size INTEGER NOT NULL,
      direction TEXT NOT NULL,
      content BLOB,
      created_at INTEGER NOT NULL
    , workflow_run_id TEXT, stage_run_id TEXT);

CREATE TABLE webhook_registrations (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      source TEXT NOT NULL,
      event_type TEXT NOT NULL,
      condition TEXT,
      template_id TEXT NOT NULL,
      auto_start INTEGER NOT NULL DEFAULT 1,
      session_config TEXT,
      enabled INTEGER NOT NULL DEFAULT 1,
      created_at INTEGER NOT NULL,
      last_triggered_at INTEGER
    );

CREATE TABLE webhook_deliveries (
      id TEXT PRIMARY KEY,
      registration_id TEXT REFERENCES webhook_registrations(id),
      delivery_id TEXT,
      source TEXT NOT NULL,
      event_type TEXT NOT NULL,
      payload TEXT,
      status TEXT NOT NULL,
      error TEXT,
      session_id TEXT REFERENCES sessions(id),
      received_at INTEGER NOT NULL,
      processed_at INTEGER
    );

CREATE TABLE chats (
      id            TEXT PRIMARY KEY,
      name          TEXT NOT NULL,
      description   TEXT,
      session_id    TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
      model         TEXT,
      copilot_config TEXT,
      repo_url      TEXT,
      repo_branch   TEXT,
      workspace_path TEXT,
      tags          TEXT DEFAULT '[]',
      status        TEXT NOT NULL DEFAULT 'active',
      created_at    INTEGER NOT NULL,
      updated_at    INTEGER NOT NULL
    , git_repositories TEXT, project_id TEXT, workspace_id TEXT, use_worktree INTEGER NOT NULL DEFAULT 1, codebase_ids TEXT, harness_config TEXT, agent_ref TEXT, agent_id TEXT, agent_version INTEGER, agent_overrides TEXT, agent_snapshot TEXT, orchestrator_mode INTEGER NOT NULL DEFAULT 0, parent_chat_id TEXT, background_task_name TEXT, background_task_index INTEGER, background_task_status TEXT, default_agent_mode TEXT NOT NULL DEFAULT 'interactive', permission_mode TEXT NOT NULL DEFAULT 'bypassPermissions', orchestrator_wave_count INTEGER, orchestrator_started_at INTEGER, sources TEXT, primary_source TEXT, forked_from_chat_id TEXT, forked_at_turn_id TEXT, conversation_seed TEXT, source_control TEXT);

CREATE TABLE workflow_definitions (
      id             TEXT PRIMARY KEY,
      name           TEXT NOT NULL,
      description    TEXT,
      version        INTEGER NOT NULL DEFAULT 1,
      session_mode   TEXT NOT NULL DEFAULT 'auto',
      copilot_config        TEXT,
      variables             TEXT DEFAULT '[]',
      tags                  TEXT DEFAULT '[]',
      orchestrator_config   TEXT,
      created_at            INTEGER NOT NULL,
      updated_at            INTEGER NOT NULL
    , scope TEXT DEFAULT 'global', project_id TEXT, selected_artifacts TEXT DEFAULT '{}', use_worktree INTEGER NOT NULL DEFAULT 1, hooks TEXT DEFAULT '[]', hooks_file TEXT, harness_config TEXT, default_agent_ref TEXT, skills TEXT, agents TEXT);

CREATE TABLE stage_definitions (
      id                       TEXT PRIMARY KEY,
      workflow_definition_id   TEXT NOT NULL REFERENCES workflow_definitions(id) ON DELETE CASCADE,
      name                     TEXT NOT NULL,
      description              TEXT,
      template_id              TEXT,
      "order"                  INTEGER NOT NULL DEFAULT 0,
      prompts                  TEXT DEFAULT '[]',
      copilot_config_overrides TEXT,
      variables                TEXT DEFAULT '{}',
      hooks                    TEXT DEFAULT '[]',
      retry_policy             TEXT,
      timeout_ms               INTEGER,
      condition                TEXT,
      created_at               INTEGER NOT NULL
    , context_filter TEXT DEFAULT 'summary-only', agent_name TEXT, result_validation TEXT, expected_output TEXT, output_schema TEXT, iteration_config TEXT, context_sources TEXT, output_format TEXT DEFAULT 'text', harness_config_overrides TEXT, approval_required INTEGER NOT NULL DEFAULT 0, agent_ref TEXT, agent_mode TEXT);

CREATE TABLE stage_edges (
      id                       TEXT PRIMARY KEY,
      workflow_definition_id   TEXT NOT NULL REFERENCES workflow_definitions(id) ON DELETE CASCADE,
      from_stage_id            TEXT NOT NULL REFERENCES stage_definitions(id) ON DELETE CASCADE,
      to_stage_id              TEXT NOT NULL REFERENCES stage_definitions(id) ON DELETE CASCADE,
      edge_type                TEXT NOT NULL DEFAULT 'on_success'
    );

CREATE TABLE workflow_runs (
      id                       TEXT PRIMARY KEY,
      workflow_definition_id   TEXT NOT NULL REFERENCES workflow_definitions(id),
      name                     TEXT NOT NULL,
      status                   TEXT NOT NULL DEFAULT 'created',
      session_mode             TEXT NOT NULL DEFAULT 'auto',
      variables                TEXT DEFAULT '{}',
      error                    TEXT,
      created_at               INTEGER NOT NULL,
      updated_at               INTEGER NOT NULL,
      started_at               INTEGER,
      completed_at             INTEGER
    , master_session_id TEXT, permission_mode TEXT, project_id TEXT, workspace_id TEXT, parent_stage_run_id TEXT, agent_snapshot TEXT, ancestor_run_id TEXT REFERENCES workflow_runs(id) ON DELETE SET NULL, definition_snapshot TEXT);

CREATE TABLE stage_runs (
      id                       TEXT PRIMARY KEY,
      workflow_run_id          TEXT NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
      stage_definition_id      TEXT NOT NULL REFERENCES stage_definitions(id),
      session_id               TEXT REFERENCES sessions(id),
      name                     TEXT NOT NULL,
      status                   TEXT NOT NULL DEFAULT 'pending',
      current_step             INTEGER NOT NULL DEFAULT 0,
      total_steps              INTEGER NOT NULL DEFAULT 0,
      retry_count              INTEGER NOT NULL DEFAULT 0,
      error                    TEXT,
      created_at               INTEGER NOT NULL,
      started_at               INTEGER,
      completed_at             INTEGER
    , summary TEXT, version INTEGER NOT NULL DEFAULT 0, wake_at INTEGER, slept_since INTEGER, interrupt_data TEXT, output_data TEXT, output_text TEXT, artifact_manifest TEXT, iteration_index INTEGER DEFAULT 0, parent_stage_run_id TEXT, heartbeat_at INTEGER, lease_owner TEXT);

CREATE TABLE automations (
      id               TEXT PRIMARY KEY,
      name             TEXT NOT NULL,
      description      TEXT,
      enabled          INTEGER NOT NULL DEFAULT 1,
      trigger_type     TEXT NOT NULL,
      cron_expression  TEXT,
      webhook_token    TEXT,
      workflow_ids     TEXT NOT NULL DEFAULT '[]',
      input_mode       TEXT NOT NULL DEFAULT 'single',
      loop_variable    TEXT,
      loop_items       TEXT DEFAULT '[]',
      variables        TEXT DEFAULT '{}',
      max_concurrency  INTEGER NOT NULL DEFAULT 1,
      on_error         TEXT NOT NULL DEFAULT 'continue',
      last_run_at      INTEGER,
      next_run_at      INTEGER,
      created_at       INTEGER NOT NULL,
      updated_at       INTEGER NOT NULL
    , batch_data_format TEXT, batch_data TEXT, batch_columns TEXT DEFAULT '[]', batch_column_mapping TEXT DEFAULT '{}', data_source_config TEXT, locked_until INTEGER, locked_by_process TEXT, scope TEXT DEFAULT 'global', project_id TEXT, use_worktree INTEGER NOT NULL DEFAULT 1, retry_policy TEXT, data_schema TEXT, iteration_mode TEXT, default_dataset TEXT, webhook_token_hash TEXT, timezone TEXT, missed_run_policy TEXT NOT NULL DEFAULT 'skip', overlap_policy TEXT NOT NULL DEFAULT 'skip');

CREATE TABLE automation_executions (
      id                    TEXT PRIMARY KEY,
      automation_id         TEXT NOT NULL REFERENCES automations(id) ON DELETE CASCADE,
      status                TEXT NOT NULL DEFAULT 'pending',
      triggered_by          TEXT NOT NULL,
      webhook_payload       TEXT,
      total_iterations      INTEGER NOT NULL DEFAULT 0,
      completed_iterations  INTEGER NOT NULL DEFAULT 0,
      failed_iterations     INTEGER NOT NULL DEFAULT 0,
      error                 TEXT,
      started_at            INTEGER,
      completed_at          INTEGER,
      created_at            INTEGER NOT NULL
    , workspace_id TEXT, dataset_snapshot TEXT);

CREATE TABLE automation_execution_runs (
      id                      TEXT PRIMARY KEY,
      execution_id            TEXT NOT NULL REFERENCES automation_executions(id) ON DELETE CASCADE,
      workflow_run_id         TEXT NOT NULL REFERENCES workflow_runs(id) ON DELETE SET NULL,
      workflow_definition_id  TEXT NOT NULL REFERENCES workflow_definitions(id),
      iteration_index         INTEGER NOT NULL DEFAULT 0,
      status                  TEXT NOT NULL DEFAULT 'pending',
      created_at              INTEGER NOT NULL
    , iteration_variables TEXT, iteration_label TEXT, attempt_count INTEGER NOT NULL DEFAULT 1);

CREATE TABLE _schema_versions (
      version    INTEGER PRIMARY KEY,
      applied_at INTEGER NOT NULL,
      name       TEXT NOT NULL
    );

CREATE TABLE session_allocations (
          id                TEXT PRIMARY KEY,
          workflow_run_id   TEXT NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
          mode              TEXT NOT NULL,
          shared_session_id TEXT,
          shared_ref_count  INTEGER NOT NULL DEFAULT 0,
          created_at        INTEGER NOT NULL
        );

CREATE TABLE stage_session_maps (
          id            TEXT PRIMARY KEY,
          allocation_id TEXT NOT NULL REFERENCES session_allocations(id) ON DELETE CASCADE,
          stage_run_id  TEXT NOT NULL,
          session_id    TEXT NOT NULL
        );

CREATE TABLE stream_cursors (
          id         INTEGER PRIMARY KEY AUTOINCREMENT,
          scope      TEXT    NOT NULL,
          scope_id   TEXT    NOT NULL,
          seq        INTEGER NOT NULL,
          kind       TEXT    NOT NULL,
          payload    TEXT    NOT NULL,
          ts         INTEGER NOT NULL
        );

CREATE TABLE stream_sequences (
          scope     TEXT    NOT NULL,
          scope_id  TEXT    NOT NULL,
          last_seq  INTEGER NOT NULL DEFAULT 0,
          PRIMARY KEY (scope, scope_id)
        );

CREATE TABLE projects (
          id          TEXT PRIMARY KEY,
          name        TEXT NOT NULL,
          description TEXT,
          settings    TEXT DEFAULT '{}',
          root_path   TEXT NOT NULL,
          status      TEXT NOT NULL DEFAULT 'active',
          created_at  INTEGER NOT NULL,
          updated_at  INTEGER NOT NULL
        );

CREATE TABLE project_codebases (
          id              TEXT PRIMARY KEY,
          project_id      TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
          alias           TEXT NOT NULL,
          type            TEXT NOT NULL,
          url             TEXT,
          local_path      TEXT,
          default_branch  TEXT,
          subdirectory    TEXT,
          clone_path      TEXT,
          status          TEXT NOT NULL DEFAULT 'pending',
          last_fetched_at INTEGER,
          last_error      TEXT,
          settings        TEXT DEFAULT '{}',
          created_at      INTEGER NOT NULL,
          updated_at      INTEGER NOT NULL
        );

CREATE TABLE project_configs (
          id          TEXT PRIMARY KEY,
          project_id  TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
          type        TEXT NOT NULL,
          name        TEXT NOT NULL,
          description TEXT,
          file_path   TEXT NOT NULL,
          metadata    TEXT DEFAULT '{}',
          created_at  INTEGER NOT NULL,
          updated_at  INTEGER NOT NULL
        , credential_refs TEXT);

CREATE TABLE worktrees (
          id             TEXT PRIMARY KEY,
          project_id     TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
          codebase_id    TEXT NOT NULL REFERENCES project_codebases(id) ON DELETE CASCADE,
          run_id         TEXT,
          run_type       TEXT,
          worktree_path  TEXT NOT NULL,
          branch_name    TEXT NOT NULL,
          status         TEXT NOT NULL DEFAULT 'active',
          created_at     INTEGER NOT NULL,
          cleaned_up_at  INTEGER
        );

CREATE TABLE execution_workspaces (
          id          TEXT PRIMARY KEY,
          owner_type  TEXT NOT NULL CHECK(owner_type IN ('chat', 'workflow_run', 'automation_execution')),
          owner_id    TEXT NOT NULL,
          project_id  TEXT,
          root_path   TEXT NOT NULL,
          status      TEXT NOT NULL DEFAULT 'creating'
            CHECK(status IN ('creating', 'active', 'completed', 'archived', 'failed')),
          git_enabled INTEGER NOT NULL DEFAULT 1,
          use_worktree INTEGER NOT NULL DEFAULT 1,
          snapshot_path TEXT,
          metadata    TEXT,
          created_at  INTEGER NOT NULL,
          updated_at  INTEGER NOT NULL,
          completed_at INTEGER,
          archived_at INTEGER
        , browser_config TEXT, browser_status TEXT, browser_current_url TEXT, browser_cdp_endpoint TEXT, browser_target_id TEXT, browser_started_at INTEGER, browser_last_activity_at INTEGER, code_root TEXT, prep_status TEXT NOT NULL DEFAULT 'ready', prep_error TEXT);

CREATE TABLE idempotency_keys (
          key           TEXT NOT NULL,
          scope         TEXT NOT NULL,
          execution_id  TEXT NOT NULL,
          created_at    INTEGER NOT NULL,
          expires_at    INTEGER NOT NULL,
          PRIMARY KEY (key, scope)
        );

CREATE TABLE "widget_instances" (
          id                TEXT PRIMARY KEY,
          descriptor_id     TEXT NOT NULL,
          session_id        TEXT NOT NULL,
          chat_id           TEXT,
          workflow_run_id   TEXT,
          stage_run_id      TEXT,
          message_id        TEXT,
          surface           TEXT NOT NULL CHECK(surface IN ('inline', 'widget')),
          props             TEXT,
          state             TEXT,
          status            TEXT NOT NULL DEFAULT 'active'
            CHECK(status IN ('active', 'suspended', 'closed', 'error')),
          error             TEXT,
          created_at        INTEGER NOT NULL,
          updated_at        INTEGER NOT NULL
        );

CREATE TABLE checkpoints (
          id                           TEXT PRIMARY KEY,
          workspace_id                 TEXT NOT NULL,
          repo_alias                   TEXT NOT NULL DEFAULT '.',
          seq                          INTEGER NOT NULL,
          kind                         TEXT NOT NULL
            CHECK(kind IN ('baseline','turn','stage','autorun','live','manual','pre_restore')),
          label                        TEXT,
          ref_kind                     TEXT NOT NULL DEFAULT 'git_tree',
          ref_value                    TEXT NOT NULL,
          tree_sha                     TEXT NOT NULL,
          parent_id                    TEXT,
          session_id                   TEXT,
          chat_id                      TEXT,
          turn_id                      TEXT,
          workflow_run_id              TEXT,
          stage_run_id                 TEXT,
          automation_execution_run_id  TEXT,
          prompt_excerpt               TEXT,
          file_count                   INTEGER NOT NULL DEFAULT 0,
          additions                    INTEGER NOT NULL DEFAULT 0,
          deletions                    INTEGER NOT NULL DEFAULT 0,
          created_at                   INTEGER NOT NULL
        , phase TEXT);

CREATE TABLE review_threads (
          id                        TEXT PRIMARY KEY,
          workspace_id              TEXT NOT NULL,
          scope                     TEXT NOT NULL CHECK(scope IN ('chat','run','automation')),
          scope_id                  TEXT NOT NULL,
          repo_alias                TEXT NOT NULL DEFAULT '.',
          path                      TEXT NOT NULL,
          base_checkpoint_id        TEXT NOT NULL,
          head_checkpoint_id        TEXT NOT NULL,
          side                      TEXT NOT NULL CHECK(side IN ('additions','deletions')),
          start_line                INTEGER NOT NULL,
          end_line                  INTEGER NOT NULL,
          anchor_text               TEXT NOT NULL,
          anchor_hash               TEXT NOT NULL,
          status                    TEXT NOT NULL DEFAULT 'pending'
            CHECK(status IN ('draft','pending','submitted','addressed','resolved','outdated')),
          resolved_by_checkpoint_id TEXT,
          submitted_message_id      TEXT,
          review_round              INTEGER NOT NULL DEFAULT 0,
          created_at                INTEGER NOT NULL,
          updated_at                INTEGER NOT NULL
        );

CREATE TABLE review_comments (
          id         TEXT PRIMARY KEY,
          thread_id  TEXT NOT NULL REFERENCES review_threads(id) ON DELETE CASCADE,
          author     TEXT NOT NULL CHECK(author IN ('user','agent')),
          body       TEXT NOT NULL,
          intent     TEXT CHECK(intent IS NULL OR intent IN ('fix','question','note','refactor','test')),
          created_at INTEGER NOT NULL,
          updated_at INTEGER NOT NULL
        );

CREATE TABLE "plan_documents" (
          id                 TEXT PRIMARY KEY,
          chat_id            TEXT NOT NULL,
          session_id         TEXT NOT NULL,
          turn_id            TEXT NOT NULL,
          title              TEXT NOT NULL,
          file_name          TEXT NOT NULL,
          file_path          TEXT,
          status             TEXT NOT NULL DEFAULT 'drafting'
            CHECK(status IN ('drafting','recorded','awaiting_review','changes_requested','approved','rejected','superseded','expired')),
          current_revision   INTEGER NOT NULL DEFAULT 1,
          harness_type       TEXT NOT NULL DEFAULT 'copilot',
          available_actions  TEXT NOT NULL DEFAULT '[]',
          recommended_action TEXT,
          decision           TEXT,
          stage_run_id       TEXT,
          workflow_run_id    TEXT,
          created_at         INTEGER NOT NULL,
          updated_at         INTEGER NOT NULL
        );

CREATE TABLE plan_revisions (
          id          TEXT PRIMARY KEY,
          plan_id     TEXT NOT NULL REFERENCES plan_documents(id) ON DELETE CASCADE,
          revision    INTEGER NOT NULL,
          content     TEXT NOT NULL,
          summary     TEXT NOT NULL DEFAULT '',
          authored_by TEXT NOT NULL DEFAULT 'agent' CHECK(authored_by IN ('agent','user')),
          created_at  INTEGER NOT NULL
        );

CREATE TABLE plan_comments (
          id                TEXT PRIMARY KEY,
          plan_id           TEXT NOT NULL REFERENCES plan_documents(id) ON DELETE CASCADE,
          revision          INTEGER NOT NULL,
          anchor_start_line INTEGER,
          anchor_end_line   INTEGER,
          anchor_text       TEXT,
          anchor_hash       TEXT,
          body              TEXT NOT NULL,
          resolved          INTEGER NOT NULL DEFAULT 0,
          created_at        INTEGER NOT NULL
        );

CREATE TABLE agent_interactions (
          id          TEXT PRIMARY KEY,
          scope_kind  TEXT NOT NULL CHECK(scope_kind IN ('chat','stage_run')),
          scope_id    TEXT NOT NULL,
          chat_id     TEXT,
          session_id  TEXT,
          turn_id     TEXT,
          kind        TEXT NOT NULL CHECK(kind IN ('plan_review','question','tool_permission')),
          status      TEXT NOT NULL DEFAULT 'pending'
            CHECK(status IN ('pending','approved','changes_requested','answered','rejected','cancelled','expired','failed')),
          payload     TEXT,
          resolution  TEXT,
          created_at  INTEGER NOT NULL,
          resolved_at INTEGER,
          expires_at  INTEGER
        );

CREATE TABLE auth_devices (
          device_id                       TEXT PRIMARY KEY,
          owner_id                        TEXT NOT NULL DEFAULT 'local',
          name                            TEXT NOT NULL,
          platform                        TEXT NOT NULL DEFAULT 'other'
            CHECK(platform IN ('web','desktop','cli','mobile','other')),
          public_jwk                      TEXT NOT NULL,
          jwk_thumbprint                  TEXT NOT NULL,
          scopes                          TEXT NOT NULL DEFAULT '[]',
          created_at                      INTEGER NOT NULL,
          last_seen_at                    INTEGER,
          last_seen_transport             TEXT,
          revoked_at                      INTEGER,
          revoked_reason                  TEXT,
          credential_version              INTEGER NOT NULL DEFAULT 1,
          previous_credential_grace_until INTEGER,
          connection_mode                 TEXT NOT NULL DEFAULT 'auto',
          relay_binding                   TEXT
        );

CREATE TABLE auth_device_credentials (
          credential_id TEXT PRIMARY KEY,
          device_id     TEXT NOT NULL,
          secret_hash   TEXT NOT NULL UNIQUE,
          version       INTEGER NOT NULL DEFAULT 1,
          created_at    INTEGER NOT NULL,
          expires_at    INTEGER,
          last_used_at  INTEGER,
          revoked_at    INTEGER
        );

CREATE TABLE auth_pairing_grants (
          grant_id             TEXT PRIMARY KEY,
          token_hash           TEXT NOT NULL UNIQUE,
          device_name_hint     TEXT NOT NULL,
          platform             TEXT NOT NULL DEFAULT 'other',
          requested_scopes     TEXT NOT NULL DEFAULT '[]',
          created_at           INTEGER NOT NULL,
          expires_at           INTEGER NOT NULL,
          consumed_at          INTEGER,
          revoked_at           INTEGER,
          attempts             INTEGER NOT NULL DEFAULT 0,
          max_attempts         INTEGER NOT NULL DEFAULT 5,
          relay_invite         TEXT,
          created_by_principal TEXT NOT NULL DEFAULT 'unknown'
        );

CREATE TABLE auth_replay_entries (
          jti_hash   TEXT PRIMARY KEY,
          expires_at INTEGER NOT NULL
        );

CREATE TABLE auth_nonces (
          nonce      TEXT PRIMARY KEY,
          expires_at INTEGER NOT NULL
        );

CREATE TABLE auth_stream_tickets (
          ticket_hash    TEXT PRIMARY KEY,
          principal_id   TEXT NOT NULL,
          principal_type TEXT NOT NULL,
          device_id      TEXT,
          scopes         TEXT NOT NULL DEFAULT '[]',
          scope          TEXT NOT NULL,
          scope_id       TEXT,
          created_at     INTEGER NOT NULL,
          expires_at     INTEGER NOT NULL,
          consumed_at    INTEGER
        );

CREATE TABLE auth_service_accounts (
          account_id   TEXT PRIMARY KEY,
          name         TEXT NOT NULL,
          secret_hash  TEXT NOT NULL UNIQUE,
          scopes       TEXT NOT NULL DEFAULT '[]',
          created_at   INTEGER NOT NULL,
          last_used_at INTEGER,
          revoked_at   INTEGER,
          legacy       INTEGER NOT NULL DEFAULT 0
        );

CREATE TABLE security_audit_events (
          event_id            TEXT PRIMARY KEY,
          timestamp           INTEGER NOT NULL,
          actor_principal_type TEXT NOT NULL,
          actor_principal_id   TEXT NOT NULL,
          actor_device_id      TEXT,
          action              TEXT NOT NULL,
          resource_type       TEXT,
          resource_id         TEXT,
          result              TEXT NOT NULL CHECK(result IN ('success','failure','denied')),
          reason_code         TEXT,
          request_id          TEXT,
          connection_id       TEXT,
          transport           TEXT,
          source_address_hash TEXT,
          metadata            TEXT,
          severity            TEXT NOT NULL DEFAULT 'info'
            CHECK(severity IN ('info','warn','critical'))
        );

CREATE TABLE relay_revoke_outbox (
          id              TEXT PRIMARY KEY,
          relay_binding   TEXT NOT NULL,
          device_id       TEXT NOT NULL,
          enqueued_at     INTEGER NOT NULL,
          attempts        INTEGER NOT NULL DEFAULT 0,
          last_attempt_at INTEGER,
          last_error      TEXT
        );

CREATE TABLE signed_links (
          jti           TEXT PRIMARY KEY,
          resource_type TEXT NOT NULL,
          resource_id   TEXT NOT NULL,
          scopes        TEXT NOT NULL DEFAULT '[]',
          created_at    INTEGER NOT NULL,
          expires_at    INTEGER NOT NULL,
          max_uses      INTEGER NOT NULL DEFAULT 1,
          uses          INTEGER NOT NULL DEFAULT 0,
          revoked_at    INTEGER,
          created_by    TEXT
        );

CREATE TABLE harness_instances (
          instance_id        TEXT PRIMARY KEY,
          driver_type        TEXT NOT NULL,
          display_name       TEXT NOT NULL,
          config             TEXT NOT NULL DEFAULT '{}',
          credential_refs    TEXT NOT NULL DEFAULT '{}',
          home_directory     TEXT,
          allowed_project_ids TEXT NOT NULL DEFAULT '[]',
          default_model      TEXT,
          permission_profile TEXT NOT NULL DEFAULT 'workspace-write',
          enabled            INTEGER NOT NULL DEFAULT 1,
          created_at         INTEGER NOT NULL,
          updated_at         INTEGER NOT NULL
        );

CREATE TABLE ssh_targets (
          target_id       TEXT PRIMARY KEY,
          name            TEXT NOT NULL,
          host            TEXT NOT NULL,
          port            INTEGER NOT NULL DEFAULT 22,
          username        TEXT NOT NULL,
          auth_method     TEXT NOT NULL DEFAULT 'agent'
            CHECK(auth_method IN ('agent','key','password')),
          private_key_ref TEXT,
          proxy_jump      TEXT,
          remote_port     INTEGER NOT NULL DEFAULT 3100,
          local_port      INTEGER,
          created_at      INTEGER NOT NULL,
          updated_at      INTEGER NOT NULL
        );

CREATE TABLE ssh_host_keys (
          id           TEXT PRIMARY KEY,
          host         TEXT NOT NULL,
          port         INTEGER NOT NULL DEFAULT 22,
          key_type     TEXT NOT NULL,
          fingerprint  TEXT NOT NULL,
          trusted_at   INTEGER NOT NULL,
          trusted_by   TEXT
        );

CREATE TABLE device_push_tokens (
          device_id     TEXT PRIMARY KEY
                        REFERENCES auth_devices(device_id) ON DELETE CASCADE,
          provider      TEXT NOT NULL CHECK(provider IN ('expo','apns','fcm')),
          token         TEXT NOT NULL,
          platform      TEXT NOT NULL,
          created_at    INTEGER NOT NULL,
          updated_at    INTEGER NOT NULL,
          -- Consecutive delivery failures. A token the push service has
          -- rejected repeatedly is dead; retrying it forever wastes quota and
          -- can get the whole sender throttled.
          failure_count INTEGER NOT NULL DEFAULT 0,
          last_error    TEXT,
          -- Per-device mute, so one noisy project cannot make the user turn
          -- off notifications entirely and miss the approval gates.
          muted_until   INTEGER
        );

CREATE TABLE agents (
          id             TEXT PRIMARY KEY,
          scope          TEXT NOT NULL CHECK(scope IN ('system','global','project')),
          project_id     TEXT NOT NULL DEFAULT '',
          slug           TEXT NOT NULL,
          name           TEXT NOT NULL,
          description    TEXT NOT NULL,
          instructions   TEXT NOT NULL,
          role           TEXT NOT NULL DEFAULT 'agent' CHECK(role IN ('agent','orchestrator')),
          projection     TEXT NOT NULL DEFAULT 'append' CHECK(projection IN ('append','replace')),
          icon           TEXT,
          color          TEXT,
          tags           TEXT DEFAULT '[]',
          enabled        INTEGER NOT NULL DEFAULT 1,
          skill_ids      TEXT DEFAULT '[]',
          mcp_server_ids TEXT DEFAULT '[]',
          tools          TEXT DEFAULT '{}',
          runtime        TEXT DEFAULT '{}',
          orchestration  TEXT,
          version        INTEGER NOT NULL DEFAULT 1,
          source_path    TEXT,
          created_at     INTEGER NOT NULL,
          updated_at     INTEGER NOT NULL
        );

CREATE TABLE "workspace_artifacts" (
          id              TEXT PRIMARY KEY,
          workspace_id    TEXT NOT NULL REFERENCES execution_workspaces(id) ON DELETE CASCADE,
          stage_run_id    TEXT,
          artifact_type   TEXT NOT NULL
            CHECK(artifact_type IN (
              'code_file', 'response_md', 'attachment', 'script_output', 'log', 'snapshot',
              'browser_screenshot', 'browser_dom', 'browser_har',
              'browser_console_log', 'browser_video', 'browser_selection',
              'computer_screenshot'
            )),
          relative_path   TEXT NOT NULL,
          file_size       INTEGER,
          mime_type       TEXT,
          metadata        TEXT,
          created_at      INTEGER NOT NULL
        );

CREATE TABLE computer_use_audit (
          id            TEXT PRIMARY KEY,
          workspace_id  TEXT NOT NULL,
          chat_id       TEXT,
          app_identity  TEXT NOT NULL,
          app_label     TEXT NOT NULL,
          action        TEXT NOT NULL,
          target        TEXT,
          path          TEXT,
          verified      INTEGER NOT NULL DEFAULT 0,
          refusal_code  TEXT,
          blocked_on    TEXT,
          artifact_path TEXT,
          created_at    INTEGER NOT NULL
        );

CREATE TABLE "computer_use_grants" (
          id            TEXT PRIMARY KEY,
          workspace_id  TEXT NOT NULL REFERENCES execution_workspaces(id) ON DELETE CASCADE,
          app_identity  TEXT NOT NULL,
          app_label     TEXT NOT NULL,
          decision      TEXT NOT NULL CHECK(decision IN ('always_allow','deny')),
          scope         TEXT NOT NULL DEFAULT 'read' CHECK(scope IN ('read','mutate','synthetic')),
          granted_at    INTEGER NOT NULL,
          last_used_at  INTEGER
        );

CREATE TABLE stream_meta (
           key TEXT PRIMARY KEY,
           value TEXT NOT NULL
         );

CREATE TABLE conversation_ownership (
           conversation_id TEXT PRIMARY KEY,
           harness_type    TEXT NOT NULL,
           updated_at      INTEGER NOT NULL
         );

CREATE TABLE "system_configs" (
           id          TEXT PRIMARY KEY,
           type        TEXT NOT NULL CHECK(type IN ('agent', 'prompt', 'skill', 'mcp')),
           name        TEXT NOT NULL,
           description TEXT,
           file_path   TEXT NOT NULL,
           version     TEXT DEFAULT '1.0.0',
           metadata    TEXT,
           created_at  INTEGER NOT NULL,
           updated_at  INTEGER NOT NULL
         );

CREATE TABLE registers (
          scope      TEXT    NOT NULL,
          scope_id   TEXT    NOT NULL,
          key        TEXT    NOT NULL,
          value      TEXT    NOT NULL,
          version    INTEGER NOT NULL DEFAULT 0,
          written_at INTEGER NOT NULL,
          PRIMARY KEY (scope, scope_id, key)
        );

CREATE TABLE entries (
          id          TEXT    PRIMARY KEY,
          scope       TEXT    NOT NULL
            CHECK(scope IN ('session', 'stage_run', 'workflow_run', 'automation_execution')),
          scope_id    TEXT    NOT NULL,
          kind        TEXT    NOT NULL
            CHECK(kind IN ('artifact', 'signal', 'awakeable', 'tool_result', 'stage_result')),
          artifact_id TEXT,
          key         TEXT,
          payload     TEXT    NOT NULL,
          resolved    INTEGER NOT NULL DEFAULT 0,
          resolved_at INTEGER,
          created_at  INTEGER NOT NULL
        );

CREATE TABLE conversation_instance_ownership (
          conversation_id TEXT PRIMARY KEY,
          instance_id     TEXT NOT NULL,
          updated_at      INTEGER NOT NULL
        , provider TEXT, adapter_key TEXT, resume_cursor TEXT, runtime_payload TEXT, runtime_mode TEXT, binding_origin TEXT NOT NULL DEFAULT 'migrated-ambiguous');

CREATE TABLE workspace_mounts (
           id TEXT PRIMARY KEY,
           workspace_id TEXT NOT NULL REFERENCES execution_workspaces(id) ON DELETE CASCADE,
           position INTEGER NOT NULL DEFAULT 0,
           alias TEXT NOT NULL,
           origin_kind TEXT NOT NULL,
           codebase_id TEXT,
           project_id TEXT,
           origin_path TEXT,
           mode TEXT NOT NULL,
           path TEXT NOT NULL,
           git TEXT,
           status TEXT NOT NULL DEFAULT 'preparing',
           error TEXT,
           has_uncommitted_changes INTEGER NOT NULL DEFAULT 0,
           created_at INTEGER NOT NULL,
           updated_at INTEGER NOT NULL
         );

CREATE TABLE device_scope_requests (
          id               TEXT PRIMARY KEY,
          device_id        TEXT NOT NULL
                           REFERENCES auth_devices(device_id) ON DELETE CASCADE,
          requested_scopes TEXT NOT NULL DEFAULT '[]',
          reason           TEXT,
          status           TEXT NOT NULL DEFAULT 'pending'
            CHECK(status IN ('pending','approved','denied','cancelled')),
          created_at       INTEGER NOT NULL,
          resolved_at      INTEGER,
          resolved_by      TEXT,
          resolution_note  TEXT,
          -- Subset actually granted on approval; NULL for every other status.
          granted_scopes   TEXT
        );

CREATE TABLE workspace_file_reviews (
          workspace_id  TEXT NOT NULL,
          alias         TEXT NOT NULL,
          path          TEXT NOT NULL,
          accepted_blob TEXT NOT NULL,
          accepted_at   INTEGER NOT NULL,
          PRIMARY KEY (workspace_id, alias, path)
        );

CREATE INDEX idx_sessions_status ON sessions(status);

CREATE INDEX idx_sessions_created_at ON sessions(created_at);

CREATE INDEX idx_workflows_session_id ON workflows(session_id);

CREATE INDEX idx_workflows_status ON workflows(status);

CREATE INDEX idx_workflows_order ON workflows(session_id, "order");

CREATE UNIQUE INDEX idx_events_session_seq ON events(session_id, sequence_id);

CREATE INDEX idx_events_session_kind ON events(session_id, kind);

CREATE INDEX idx_events_timestamp ON events(timestamp);

CREATE INDEX idx_chat_session_id ON chat_messages(session_id);

CREATE INDEX idx_chat_session_time ON chat_messages(session_id, timestamp);

CREATE INDEX idx_artifacts_session_id ON artifacts(session_id);

CREATE INDEX idx_chats_status ON chats(status);

CREATE INDEX idx_chats_session_id ON chats(session_id);

CREATE INDEX idx_chats_created_at ON chats(created_at);

CREATE INDEX idx_workflow_defs_created_at ON workflow_definitions(created_at);

CREATE INDEX idx_stage_defs_workflow ON stage_definitions(workflow_definition_id);

CREATE INDEX idx_stage_defs_order ON stage_definitions(workflow_definition_id, "order");

CREATE INDEX idx_stage_edges_workflow ON stage_edges(workflow_definition_id);

CREATE INDEX idx_stage_edges_from ON stage_edges(from_stage_id);

CREATE INDEX idx_stage_edges_to ON stage_edges(to_stage_id);

CREATE UNIQUE INDEX idx_stage_edges_unique ON stage_edges(from_stage_id, to_stage_id);

CREATE INDEX idx_workflow_runs_definition ON workflow_runs(workflow_definition_id);

CREATE INDEX idx_workflow_runs_status ON workflow_runs(status);

CREATE INDEX idx_workflow_runs_created_at ON workflow_runs(created_at);

CREATE INDEX idx_stage_runs_workflow_run ON stage_runs(workflow_run_id);

CREATE INDEX idx_stage_runs_session ON stage_runs(session_id);

CREATE INDEX idx_stage_runs_status ON stage_runs(status);

CREATE INDEX idx_automations_enabled ON automations(enabled);

CREATE INDEX idx_automations_trigger_type ON automations(trigger_type);

CREATE INDEX idx_automations_created_at ON automations(created_at);

CREATE INDEX idx_automation_executions_automation ON automation_executions(automation_id);

CREATE INDEX idx_automation_executions_status ON automation_executions(status);

CREATE INDEX idx_automation_executions_created_at ON automation_executions(created_at);

CREATE INDEX idx_automation_exec_runs_execution ON automation_execution_runs(execution_id);

CREATE INDEX idx_automation_exec_runs_workflow_run ON automation_execution_runs(workflow_run_id);

CREATE INDEX idx_automation_exec_runs_status ON automation_execution_runs(status);

CREATE INDEX idx_automation_exec_runs_iteration ON automation_execution_runs(iteration_index);

CREATE INDEX idx_chat_messages_chat_id ON chat_messages(chat_id);

CREATE INDEX idx_webhook_deliveries_registration ON webhook_deliveries(registration_id);

CREATE INDEX idx_webhook_deliveries_status ON webhook_deliveries(status);

CREATE INDEX idx_workflow_runs_status_created ON workflow_runs(status, created_at);

CREATE INDEX idx_stage_runs_status_created ON stage_runs(status, created_at);

CREATE UNIQUE INDEX idx_webhook_deliveries_delivery_id ON webhook_deliveries(delivery_id);

CREATE UNIQUE INDEX idx_session_allocations_run ON session_allocations(workflow_run_id);

CREATE INDEX idx_stage_session_maps_allocation ON stage_session_maps(allocation_id);

CREATE UNIQUE INDEX idx_stage_session_maps_stage_run ON stage_session_maps(stage_run_id);

CREATE INDEX idx_automations_lock ON automations(locked_until);

CREATE UNIQUE INDEX idx_stream_cursors_scope_id_seq ON stream_cursors(scope, scope_id, seq);

CREATE INDEX idx_stream_cursors_ts ON stream_cursors(ts);

CREATE INDEX idx_stage_runs_wake_at ON stage_runs(wake_at);

CREATE INDEX idx_projects_status ON projects(status);

CREATE INDEX idx_projects_created_at ON projects(created_at);

CREATE INDEX idx_projects_name ON projects(name);

CREATE INDEX idx_project_codebases_project ON project_codebases(project_id);

CREATE UNIQUE INDEX idx_project_codebases_alias ON project_codebases(project_id, alias);

CREATE INDEX idx_project_codebases_status ON project_codebases(status);

CREATE INDEX idx_project_configs_project ON project_configs(project_id);

CREATE INDEX idx_project_configs_type ON project_configs(project_id, type);

CREATE UNIQUE INDEX idx_project_configs_unique_name ON project_configs(project_id, type, name);

CREATE INDEX idx_worktrees_project ON worktrees(project_id);

CREATE INDEX idx_worktrees_codebase ON worktrees(codebase_id);

CREATE INDEX idx_worktrees_run ON worktrees(run_id);

CREATE INDEX idx_worktrees_status ON worktrees(status);

CREATE INDEX idx_workflow_defs_project ON workflow_definitions(project_id);

CREATE INDEX idx_automations_project ON automations(project_id);

CREATE UNIQUE INDEX idx_execution_workspaces_owner_unique ON execution_workspaces(owner_type, owner_id);

CREATE INDEX idx_execution_workspaces_owner ON execution_workspaces(owner_type, owner_id);

CREATE INDEX idx_execution_workspaces_project ON execution_workspaces(project_id);

CREATE INDEX idx_execution_workspaces_status ON execution_workspaces(status);

CREATE INDEX idx_stage_runs_parent ON stage_runs(parent_stage_run_id);

CREATE INDEX idx_workflow_runs_parent_stage ON workflow_runs(parent_stage_run_id);

CREATE INDEX idx_stage_runs_run_status ON stage_runs(workflow_run_id, status);

CREATE INDEX idx_chat_messages_chat_time ON chat_messages(chat_id, timestamp);

CREATE INDEX idx_execution_workspaces_browser_status ON execution_workspaces(browser_status);

CREATE INDEX idx_idempotency_keys_expires ON idempotency_keys(expires_at);

CREATE INDEX idx_widget_instances_session ON widget_instances(session_id);

CREATE INDEX idx_widget_instances_chat ON widget_instances(chat_id);

CREATE INDEX idx_widget_instances_run ON widget_instances(workflow_run_id);

CREATE INDEX idx_widget_instances_stage ON widget_instances(stage_run_id);

CREATE INDEX idx_chats_parent_chat_id ON chats(parent_chat_id);

CREATE INDEX idx_checkpoints_workspace ON checkpoints(workspace_id);

CREATE UNIQUE INDEX idx_checkpoints_ws_alias_seq ON checkpoints(workspace_id, repo_alias, seq);

CREATE INDEX idx_checkpoints_turn ON checkpoints(turn_id);

CREATE INDEX idx_checkpoints_stage_run ON checkpoints(stage_run_id);

CREATE INDEX idx_checkpoints_kind ON checkpoints(kind);

CREATE INDEX idx_review_threads_workspace ON review_threads(workspace_id);

CREATE INDEX idx_review_threads_scope ON review_threads(scope, scope_id);

CREATE INDEX idx_review_threads_file ON review_threads(workspace_id, repo_alias, path);

CREATE INDEX idx_review_threads_status ON review_threads(status);

CREATE INDEX idx_review_comments_thread ON review_comments(thread_id);

CREATE UNIQUE INDEX idx_plan_revisions_unique ON plan_revisions(plan_id, revision);

CREATE INDEX idx_plan_comments_plan ON plan_comments(plan_id, revision);

CREATE INDEX idx_agent_interactions_chat ON agent_interactions(chat_id, status);

CREATE INDEX idx_agent_interactions_scope ON agent_interactions(scope_kind, scope_id, status);

CREATE UNIQUE INDEX idx_agent_interactions_pending
           ON agent_interactions(chat_id, turn_id, kind) WHERE status = 'pending';

CREATE INDEX idx_plan_documents_chat ON plan_documents(chat_id, created_at);

CREATE INDEX idx_plan_documents_status ON plan_documents(chat_id, status);

CREATE INDEX idx_plan_documents_stage ON plan_documents(stage_run_id);

CREATE UNIQUE INDEX idx_auth_devices_thumbprint_active
           ON auth_devices(jwk_thumbprint) WHERE revoked_at IS NULL;

CREATE INDEX idx_auth_devices_owner ON auth_devices(owner_id, created_at);

CREATE INDEX idx_auth_device_credentials_device
           ON auth_device_credentials(device_id, created_at);

CREATE INDEX idx_auth_pairing_pending
           ON auth_pairing_grants(expires_at) WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE INDEX idx_auth_replay_expiry ON auth_replay_entries(expires_at);

CREATE INDEX idx_auth_nonces_expiry ON auth_nonces(expires_at);

CREATE INDEX idx_auth_stream_tickets_expiry ON auth_stream_tickets(expires_at);

CREATE INDEX idx_security_audit_time ON security_audit_events(timestamp DESC);

CREATE INDEX idx_security_audit_action ON security_audit_events(action, timestamp DESC);

CREATE INDEX idx_security_audit_device ON security_audit_events(actor_device_id, timestamp DESC);

CREATE INDEX idx_relay_revoke_outbox_time ON relay_revoke_outbox(enqueued_at);

CREATE INDEX idx_harness_instances_driver ON harness_instances(driver_type);

CREATE UNIQUE INDEX idx_ssh_host_keys_host ON ssh_host_keys(host, port, key_type);

CREATE INDEX idx_device_push_provider ON device_push_tokens(provider);

CREATE INDEX idx_agents_scope ON agents(scope, project_id);

CREATE UNIQUE INDEX idx_agents_slug_unique ON agents(scope, project_id, slug);

CREATE INDEX idx_agents_role ON agents(role);

CREATE INDEX idx_chats_agent_ref ON chats(agent_ref);

CREATE INDEX idx_stage_defs_agent_ref ON stage_definitions(agent_ref);

CREATE INDEX idx_workflow_defs_agent_ref ON workflow_definitions(default_agent_ref);

CREATE INDEX idx_workspace_artifacts_workspace ON workspace_artifacts(workspace_id);

CREATE INDEX idx_workspace_artifacts_stage ON workspace_artifacts(stage_run_id);

CREATE INDEX idx_workspace_artifacts_type ON workspace_artifacts(artifact_type);

CREATE INDEX idx_cu_audit_ws_time ON computer_use_audit(workspace_id, created_at DESC);

CREATE INDEX idx_cu_audit_refusal ON computer_use_audit(refusal_code);

CREATE UNIQUE INDEX idx_cu_grants_unique ON computer_use_grants(workspace_id, app_identity);

CREATE INDEX idx_chats_project_id ON chats(project_id);

CREATE INDEX idx_conv_ownership_harness ON conversation_ownership(harness_type);

CREATE INDEX idx_system_configs_type ON system_configs(type);

CREATE UNIQUE INDEX idx_system_configs_unique ON system_configs(type, name);

CREATE INDEX idx_workflow_runs_ancestor ON workflow_runs(ancestor_run_id) WHERE ancestor_run_id IS NOT NULL;

CREATE INDEX idx_registers_scope_id ON registers(scope, scope_id);

CREATE INDEX idx_entries_scope_id ON entries(scope, scope_id);

CREATE INDEX idx_entries_scope_key ON entries(scope, scope_id, key)
           WHERE key IS NOT NULL;

CREATE UNIQUE INDEX idx_entries_awakeable_key ON entries(key)
           WHERE kind = 'awakeable' AND key IS NOT NULL;

CREATE UNIQUE INDEX idx_entries_artifact_id ON entries(scope, scope_id, artifact_id)
           WHERE artifact_id IS NOT NULL;

CREATE INDEX idx_conv_instance_ownership_instance ON conversation_instance_ownership(instance_id);

CREATE UNIQUE INDEX idx_entries_tool_result_key
           ON entries(scope, scope_id, key)
           WHERE kind = 'tool_result' AND key IS NOT NULL;

CREATE INDEX idx_automations_webhook_token_hash ON automations(webhook_token_hash);

CREATE INDEX idx_automations_due ON automations(trigger_type, enabled, next_run_at);

CREATE INDEX idx_stream_cursors_kind_ts
           ON stream_cursors(kind, ts);

CREATE INDEX idx_workspace_mounts_workspace ON workspace_mounts(workspace_id);

CREATE INDEX idx_workspace_mounts_codebase ON workspace_mounts(codebase_id);

CREATE UNIQUE INDEX idx_workspace_mounts_alias ON workspace_mounts(workspace_id, alias);

CREATE UNIQUE INDEX idx_device_scope_requests_pending
           ON device_scope_requests(device_id) WHERE status = 'pending';

CREATE INDEX idx_device_scope_requests_status
           ON device_scope_requests(status, created_at);

CREATE INDEX idx_device_scope_requests_device
           ON device_scope_requests(device_id, created_at);

CREATE INDEX idx_chats_forked_from ON chats(forked_from_chat_id);

CREATE INDEX idx_workspace_file_reviews_ws ON workspace_file_reviews(workspace_id);
