// ────────────────────────────────────────────────────────────────
// Playwright Configuration — Optimized for AI agent test execution
// Tests generated by the agent are placed in a per-run workspace
// and executed via: npx playwright test --config=playwright.config.ts
// ────────────────────────────────────────────────────────────────

import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  // Tests generated by the AI agent go here (overridden per-run via CLI --output)
  testDir: './agent-tests',

  // Individual test timeout (1 minute)
  timeout: 60_000,

  // Assertion auto-retry timeout
  expect: { timeout: 10_000 },

  // Run tests serially — agent needs deterministic order
  fullyParallel: false,
  workers: 1,

  // Fail fast — stop on first failure for agent to analyze
  maxFailures: 1,

  // Forbid test.only in CI
  forbidOnly: !!process.env.CI,

  // Retries for flaky tests
  retries: 0,

  // Reporter: JSON for programmatic parsing + HTML for visual inspection
  reporter: [
    ['json', { outputFile: 'test-results/report.json' }],
    ['html', { open: 'never', outputFolder: 'test-results/html-report' }],
  ],

  // Shared settings for all tests
  use: {
    // Base URL (overridden per workflow variables)
    baseURL: process.env.TARGET_URL || 'http://localhost:5173',

    // Capture screenshots on failure
    screenshot: 'on',

    // Capture trace on first retry for debugging
    trace: 'retain-on-failure',

    // Video recording
    video: 'retain-on-failure',

    // Viewport
    viewport: { width: 1280, height: 720 },

    // Timeouts
    actionTimeout: 10_000,
    navigationTimeout: 30_000,
  },

  // Only Chromium for agent use (fast, reliable)
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  // Output directory for test artifacts (screenshots, traces, videos)
  outputDir: 'test-results/artifacts',
});
