// ────────────────────────────────────────────────────────────────
// JSON Schema and field docs generated from the zod schemas (R-6).
//
// Build-time tooling, exported as `@generatorai/workflow-spec/jsonschema`
// so the runtime entry keeps depending on zod alone. The generated files
// are committed (`generated/*.schema.json`, `FIELDS.md`); runtime readers
// import the JSON. `pnpm generate:workflow-spec --check` fails on drift.
//
// `zod-to-json-schema` converts zod 3 schemas (zod 4's native converter
// only accepts zod 4 schemas).
// ────────────────────────────────────────────────────────────────

import { z } from 'zod';
import { zodToJsonSchema } from 'zod-to-json-schema';
import { ENGINE_LEVEL, WORKFLOW_FORMAT_VERSION } from './constants.js';
import { EXPRESSION_GRAMMAR, grammarFilters, grammarFunctions, type GrammarRow } from './expr/grammar.js';
import {
  FINALIZE_PHASES,
  INVOCATION_ERROR_CODES,
  InvocationRequestSchema,
  InvocationTriggerSchema,
  MAX_INVOCATION_DEPTH,
  PREPARE_PHASES,
  RunProfileSchema,
} from './schemas/invocation.js';
import { ForkRunRequestSchema, RunCommandSchema } from './schemas/commands.js';
import { WorkflowGraphSchema } from './schemas/graph.js';
import { STAGE_RUN_TRANSITIONS } from './state/stageRun.js';
import { WORKFLOW_RUN_TRANSITIONS } from './state/workflowRun.js';
import { ValidationIssueSchema, VALIDATION_CODES } from './validate/issues.js';
import { descriptionOf, unwrap, walkFields } from './util/zodWalk.js';

const GENERATED_NOTE = 'Generated by scripts/generate-workflow-spec.ts from @generatorai/workflow-spec. Do not edit.';

function schemaOf(schema: z.ZodTypeAny, name: string, id: string): Record<string, unknown> {
  const json = zodToJsonSchema(schema, {
    name,
    target: 'jsonSchema7',
    $refStrategy: 'root',
    effectStrategy: 'input',
    pipeStrategy: 'input',
    removeAdditionalStrategy: 'strict',
  }) as Record<string, unknown>;
  return { $id: id, $comment: GENERATED_NOTE, ...json };
}

/** Every generated JSON Schema, by output file name. */
export function toJSONSchema(): Record<string, Record<string, unknown>> {
  return {
    'workflow.schema.json': schemaOf(WorkflowGraphSchema, 'WorkflowGraph', 'https://generatorai.dev/schemas/workflow.schema.json'),
    'invocation.schema.json': schemaOf(
      InvocationRequestSchema,
      'InvocationRequest',
      'https://generatorai.dev/schemas/invocation.schema.json',
    ),
    'run-command.schema.json': schemaOf(RunCommandSchema, 'RunCommand', 'https://generatorai.dev/schemas/run-command.schema.json'),
    'validation-issue.schema.json': schemaOf(
      ValidationIssueSchema,
      'ValidationIssue',
      'https://generatorai.dev/schemas/validation-issue.schema.json',
    ),
  };
}

// ── FIELDS.md ────────────────────────────────────────────────────

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

/** A short type label of a field (bounds, patterns, enum values). */
export function typeLabel(schema: z.ZodTypeAny): string {
  const s = unwrap(schema);
  if (s instanceof z.ZodString) {
    const checks = s._def.checks as Array<{ kind: string; value?: number; regex?: RegExp }>;
    const min = checks.find((c) => c.kind === 'min')?.value;
    const max = checks.find((c) => c.kind === 'max')?.value;
    const re = checks.find((c) => c.kind === 'regex')?.regex;
    const fmt = checks.find((c) => c.kind === 'url' || c.kind === 'uuid')?.kind;
    const bounds =
      min !== undefined && max !== undefined
        ? ` (${min}..${max} chars)`
        : max !== undefined
          ? ` (≤${max} chars)`
          : min !== undefined
            ? ` (≥${min} chars)`
            : '';
    return `string${fmt ? ` ${fmt}` : ''}${re ? ` \`${re.source}\`` : ''}${bounds}`;
  }
  if (s instanceof z.ZodNumber) {
    const checks = s._def.checks as Array<{ kind: string; value?: number; inclusive?: boolean }>;
    const int = checks.some((c) => c.kind === 'int');
    const min = checks.find((c) => c.kind === 'min');
    const max = checks.find((c) => c.kind === 'max');
    const bounds = min || max ? ` (${min ? `${min.inclusive ? '≥' : '>'}${min.value}` : ''}${min && max ? ', ' : ''}${max ? `≤${max.value}` : ''})` : '';
    return `${int ? 'integer' : 'number'}${bounds}`;
  }
  if (s instanceof z.ZodBoolean) return 'boolean';
  if (s instanceof z.ZodEnum) return (s.options as string[]).map((o) => `'${o}'`).join(' | ');
  if (s instanceof z.ZodLiteral) return JSON.stringify(s.value);
  if (s instanceof z.ZodArray) {
    const max = s._def.maxLength?.value;
    return `${typeLabel(s.element)}[]${max !== undefined ? ` (≤${max})` : ''}`;
  }
  if (s instanceof z.ZodRecord) return `record<string, ${typeLabel(s.valueSchema)}>`;
  if (s instanceof z.ZodDiscriminatedUnion) return `one of (by \`${s.discriminator}\`)`;
  if (s instanceof z.ZodUnion) return 'one of';
  if (s instanceof z.ZodObject) return 'object';
  if (s instanceof z.ZodUnknown || s instanceof z.ZodAny) return 'any';
  return s.constructor.name.replace(/^Zod/, '').toLowerCase();
}

/** The zod default of a field, as inline code, or empty. */
export function defaultOf(schema: z.ZodTypeAny): string {
  let s: z.ZodTypeAny = schema;
  for (let i = 0; i < 10; i++) {
    if (s instanceof z.ZodDefault) return `\`${JSON.stringify(s._def.defaultValue())}\``;
    if (s instanceof z.ZodOptional || s instanceof z.ZodNullable) s = s.unwrap();
    else if (s instanceof z.ZodEffects) s = s._def.schema;
    else break;
  }
  return '';
}

function fieldTable(root: z.ZodTypeAny, prefix = ''): string {
  const rows: string[] = ['| Field | Type | Required | Default | Description |', '|---|---|---|---|---|'];
  walkFields(
    root,
    (f) => {
      const required = !f.schema.isOptional();
      rows.push(
        `| \`${cell(f.path)}\` | ${cell(typeLabel(f.schema))} | ${required ? 'yes' : ''} | ${cell(defaultOf(f.schema))} | ${cell(descriptionOf(f.schema) ?? '')} |`,
      );
    },
    prefix,
  );
  return rows.join('\n');
}

/** A grammar table (syntax, meaning) as markdown. */
export function grammarTable(rows: GrammarRow[]): string {
  return ['| Syntax | Meaning |', '|---|---|', ...rows.map((r) => `| \`${cell(r.syntax)}\` | ${cell(r.meaning)} |`)].join('\n');
}

/** The generated field reference: every field, the expression grammar, codes and state tables. */
export function renderFieldsMarkdown(): string {
  const codes = Object.entries(VALIDATION_CODES).map(
    ([code, info]) => `| \`${code}\` | ${info.layer} | ${info.severity} | ${cell(info.description)} |`,
  );
  const stageRows = STAGE_RUN_TRANSITIONS.map(
    (t) => `| ${t.from} | ${t.to} | \`${t.event}\` | ${t.owner} | ${t.applies.join(', ')} | ${cell(t.note ?? '')} |`,
  );
  const runRows = WORKFLOW_RUN_TRANSITIONS.map((t) => `| ${t.from} | ${t.to} | \`${t.event}\` | ${cell(t.note ?? '')} |`);
  return [
    '# Workflow spec field reference',
    '',
    `> ${GENERATED_NOTE}`,
    '',
    `Document format version: ${WORKFLOW_FORMAT_VERSION}. Engine level: \`${ENGINE_LEVEL}\` (fields the engine cannot execute yet are rejected with \`engine-unsupported\`).`,
    '',
    '## WorkflowGraph',
    '',
    'Paths use `[]` for list elements and `{}` for map values. A field reached through several union members is listed once per member.',
    '',
    fieldTable(WorkflowGraphSchema),
    '',
    '## Expression v2',
    '',
    '### Literals',
    '',
    grammarTable(EXPRESSION_GRAMMAR.literals),
    '',
    '### Access and calls',
    '',
    grammarTable(EXPRESSION_GRAMMAR.access),
    '',
    '### Operators (lowest precedence first)',
    '',
    grammarTable(EXPRESSION_GRAMMAR.operators),
    '',
    '### Semantics',
    '',
    grammarTable(EXPRESSION_GRAMMAR.semantics),
    '',
    '### Roots',
    '',
    grammarTable(EXPRESSION_GRAMMAR.roots),
    '',
    '### Functions',
    '',
    grammarTable(grammarFunctions()),
    '',
    '### Templates',
    '',
    grammarTable(EXPRESSION_GRAMMAR.templates),
    '',
    '### Template filters',
    '',
    grammarTable(grammarFilters()),
    '',
    '## Validation codes',
    '',
    '| Code | Layer | Severity | Meaning |',
    '|---|---|---|---|',
    ...codes,
    '',
    '## InvocationRequest',
    '',
    fieldTable(InvocationRequestSchema),
    '',
    '## Invocation trigger (server-derived)',
    '',
    fieldTable(InvocationTriggerSchema),
    '',
    '## Run commands',
    '',
    fieldTable(RunCommandSchema),
    '',
    '## Fork request',
    '',
    fieldTable(ForkRunRequestSchema),
    '',
    '## Stage-run state machine',
    '',
    '| From | To | Event | Owner | Applies to | Note |',
    '|---|---|---|---|---|---|',
    ...stageRows,
    '',
    '## Workflow-run state machine',
    '',
    '| From | To | Event | Note |',
    '|---|---|---|---|',
    ...runRows,
    '',
  ].join('\n');
}

// ── INVOCATION.md ────────────────────────────────────────────────

/** How to start a run: the request, the trigger union, the profile, the codes and the lifecycle phases (P04 WP-4.7). */
export function renderInvocationMarkdown(): string {
  return [
    '# Starting a workflow run',
    '',
    `<!-- ${GENERATED_NOTE} -->`,
    '',
    'Every run starts through ONE path: `WorkflowInvocationService.invoke`, behind `POST /api/workflow-invocations`',
    'and the client-core method `workflows.invoke`. Web, desktop, mobile, the CLI and TUI, the SDK, the MCP server,',
    'automations, scripts and forks all send the same `InvocationRequest`.',
    '',
    '- `POST /api/workflow-invocations`: JSON, or multipart with a `request` field plus `skills|agents|prompts` files → 202 `InvocationResult`.',
    '- `POST /api/workflow-invocations/plan`: the same body → `InvocationPlan` (nothing is written).',
    '- `POST /api/workflow-invocations/uploads`: multipart → `{uploads: [{uploadId, category, name}]}` (kept for 1 hour).',
    '- `GET /api/workflow-invocations/:runId/digest?wait=N`: the run digest; `wait` long-polls up to N seconds (≤ 60) for `finalized`.',
    '',
    'Errors use one envelope: `{error: {code, message, issues: [{code, path, message, severity}]}}`.',
    '',
    '## InvocationRequest',
    '',
    fieldTable(InvocationRequestSchema),
    '',
    '## Trigger (server-derived, never read from the body)',
    '',
    'A paired device or the local owner is `user`; a service account or an MCP client is `external_agent`;',
    'automations, chats, orchestrators, stages and forks build their own trigger in process.',
    '',
    fieldTable(InvocationTriggerSchema),
    '',
    '## Idempotency',
    '',
    'The key is the `Idempotency-Key` header, else `idempotencyKey` in the body, else one derived for in-process',
    'callers (`chat:<chat>:<tool call>`, `stage:<stage run>:<tool call>`, `auto:<execution>:<iteration>:<attempt>`).',
    'A replay within 24 hours returns the same run (`replayed: true`); the same key with a different body is',
    '`409 IDEMPOTENCY_KEY_REUSED`.',
    '',
    '## Scopes',
    '',
    '- Starting a run: `exec:agent` + `read:workflows`.',
    '- A `script` target: also `write:workflows` (it materializes a definition, once per script content).',
    '- `overrides.permissionMode: bypassPermissions` off loopback, or a codebase with `mode: in_place`: also `admin:settings`.',
    '',
    `Nested runs are at most ${MAX_INVOCATION_DEPTH} deep; a workflow that is its own ancestor is refused (\`RECURSION\`).`,
    '',
    '## Error codes',
    '',
    INVOCATION_ERROR_CODES.map((c) => `- \`${c}\``).join('\n'),
    '',
    '## Lifecycle phases',
    '',
    'The run then goes through ONE lifecycle. `starting` runs, in order, each phase journalled (a crash resumes at',
    'the phase that did not finish):',
    '',
    PREPARE_PHASES.map((p) => `- \`${p}\``).join('\n'),
    '',
    '`finalizing` (or `cancelling`) runs:',
    '',
    FINALIZE_PHASES.map((p) => `- \`${p}\``).join('\n'),
    '',
    '`workflow_run.finalized` fires once, after all of them: every waiter keys on it.',
    '',
    '## Run profiles',
    '',
    'Saved run inputs: a CLI profile file (`--profile <path>`) or a profile a workflow script exports.',
    '',
    fieldTable(RunProfileSchema),
    '',
  ].join('\n');
}
