// ────────────────────────────────────────────────────────────────
// GeneratorAIDeviceKey — AndroidKeyStore P-256 signing key.
//
// UNCOMPILED: written without the Android SDK on the authoring machine.
// Review the first `expo prebuild && expo run:android` carefully.
//
// What this module guarantees, and how:
//
//   • Non-extractable. The key is generated by `KeyPairGenerator("EC",
//     "AndroidKeyStore")`; the private half is never returned to the app,
//     only a handle the `Signature` engine can use.
//   • StrongBox when the device has one (`setIsStrongBoxBacked(true)`,
//     API 28+), falling back to the TEE-backed keystore when generation
//     throws `StrongBoxUnavailableException`. The backing actually obtained
//     is read back from `KeyInfo` and reported honestly:
//        strongbox  — dedicated secure element
//        keystore   — TEE / trusted environment
//        software   — the keystore's software implementation (an emulator).
//     JS surfaces whichever is real in Settings → Security.
//   • P-256 / ES256. `secp256r1` with `SHA256withECDSA`. The JCA returns
//     DER; `derToRaw` converts it to the raw `r || s` (64 bytes) JOSE form
//     that `createDpopProof` base64url-encodes.
//   • Usable while locked. No `setUserAuthenticationRequired`: lock-screen
//     Allow/Deny actions (src/auth/backgroundFetch.ts) sign while the phone
//     is locked, and app lock / step-up are enforced in JS instead.
//   • `setUnlockedDeviceRequired` is deliberately NOT set for the same reason.
//
// JS facade: apps/mobile/src/native/deviceKeyModule.ts.
// ────────────────────────────────────────────────────────────────

package dev.generatorai.devicekey

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyInfo
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import android.util.Base64
import expo.modules.kotlin.exception.CodedException
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import java.math.BigInteger
import java.security.KeyFactory
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.PrivateKey
import java.security.Signature
import java.security.interfaces.ECPublicKey
import java.security.spec.ECGenParameterSpec

private const val KEYSTORE = "AndroidKeyStore"
private const val CURVE = "secp256r1"
private const val SIGNATURE_ALGORITHM = "SHA256withECDSA"

private const val BACKING_STRONGBOX = "strongbox"
private const val BACKING_KEYSTORE = "keystore"
private const val BACKING_SOFTWARE = "software"

internal class DeviceKeyNotFoundException(alias: String) :
  CodedException("No device key exists under alias \"$alias\"")

internal class DeviceKeyOperationException(detail: String, cause: Throwable? = null) :
  CodedException("Device key operation failed: $detail", cause)

internal class DeviceKeySignatureFormatException :
  CodedException("The keystore returned a signature that is not DER ECDSA")

class GeneratorAIDeviceKeyModule : Module() {
  override fun definition() = ModuleDefinition {
    Name("GeneratorAIDeviceKey")

    // Every supported Android version has AndroidKeyStore; whether it is
    // hardware-backed is answered per key by `backing`, not up front.
    AsyncFunction("isSupported") { true }

    AsyncFunction("generate") { alias: String ->
      // Replace, never accumulate: a revoked key must not linger.
      deleteKey(alias)
      generateKey(alias)
      handleFor(alias)
    }

    AsyncFunction("exists") { alias: String ->
      keyStore().containsAlias(alias)
    }

    AsyncFunction("load") { alias: String ->
      if (keyStore().containsAlias(alias)) handleFor(alias) else null
    }

    AsyncFunction("backing") { alias: String ->
      if (keyStore().containsAlias(alias)) backingOf(privateKey(alias)) else null
    }

    AsyncFunction("sign") { alias: String, dataBase64: String ->
      val key = privateKey(alias)
      val message = try {
        Base64.decode(dataBase64, Base64.DEFAULT)
      } catch (err: IllegalArgumentException) {
        throw DeviceKeyOperationException("input is not valid base64", err)
      }
      val der = try {
        Signature.getInstance(SIGNATURE_ALGORITHM).run {
          initSign(key)
          update(message)
          sign()
        }
      } catch (err: Exception) {
        throw DeviceKeyOperationException(err.message ?: err.javaClass.simpleName, err)
      }
      Base64.encodeToString(derToRaw(der), Base64.NO_WRAP)
    }

    AsyncFunction("remove") { alias: String ->
      deleteKey(alias)
    }
  }

  // ── Keystore ──────────────────────────────────────────────────

  private fun keyStore(): KeyStore =
    KeyStore.getInstance(KEYSTORE).apply { load(null) }

  private fun privateKey(alias: String): PrivateKey {
    val entry = keyStore().getEntry(alias, null) as? KeyStore.PrivateKeyEntry
      ?: throw DeviceKeyNotFoundException(alias)
    return entry.privateKey
  }

  private fun deleteKey(alias: String) {
    val store = keyStore()
    if (store.containsAlias(alias)) store.deleteEntry(alias)
  }

  private fun specBuilder(alias: String): KeyGenParameterSpec.Builder =
    KeyGenParameterSpec.Builder(alias, KeyProperties.PURPOSE_SIGN)
      .setAlgorithmParameterSpec(ECGenParameterSpec(CURVE))
      .setDigests(KeyProperties.DIGEST_SHA256)

  private fun generateKey(alias: String) {
    val generator = KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC, KEYSTORE)

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
      try {
        generator.initialize(specBuilder(alias).setIsStrongBoxBacked(true).build())
        generator.generateKeyPair()
        return
      } catch (_: StrongBoxUnavailableException) {
        // No secure element on this device: fall through to the TEE.
      } catch (err: Exception) {
        // Some OEM keystores throw a generic ProviderException for StrongBox;
        // treat any failure here as "try without it" rather than as fatal.
        if (err is StrongBoxUnavailableException) throw err
      }
    }

    try {
      generator.initialize(specBuilder(alias).build())
      generator.generateKeyPair()
    } catch (err: Exception) {
      throw DeviceKeyOperationException(err.message ?: err.javaClass.simpleName, err)
    }
  }

  private fun backingOf(key: PrivateKey): String {
    val info = try {
      KeyFactory.getInstance(key.algorithm, KEYSTORE).getKeySpec(key, KeyInfo::class.java)
    } catch (_: Exception) {
      return BACKING_SOFTWARE
    }
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
      return when (info.securityLevel) {
        KeyProperties.SECURITY_LEVEL_STRONGBOX -> BACKING_STRONGBOX
        KeyProperties.SECURITY_LEVEL_TRUSTED_ENVIRONMENT,
        KeyProperties.SECURITY_LEVEL_UNKNOWN_SECURE -> BACKING_KEYSTORE
        else -> BACKING_SOFTWARE
      }
    }
    @Suppress("DEPRECATION")
    return if (info.isInsideSecureHardware) BACKING_KEYSTORE else BACKING_SOFTWARE
  }

  // ── Public key → JWK ──────────────────────────────────────────

  private fun handleFor(alias: String): Map<String, Any> {
    val certificate = keyStore().getCertificate(alias)
      ?: throw DeviceKeyNotFoundException(alias)
    val publicKey = certificate.publicKey as? ECPublicKey
      ?: throw DeviceKeyOperationException("public key is not an EC key")
    val point = publicKey.w
    return mapOf(
      "publicJwk" to mapOf(
        "kty" to "EC",
        "crv" to "P-256",
        "x" to base64url(fixedLength(point.affineX)),
        "y" to base64url(fixedLength(point.affineY)),
      ),
      "backing" to backingOf(privateKey(alias)),
    )
  }

  /** Big-endian, exactly 32 bytes: strip BigInteger's sign byte, left-pad short values. */
  private fun fixedLength(value: BigInteger, length: Int = 32): ByteArray {
    val raw = value.toByteArray()
    val start = if (raw.size > length) raw.size - length else 0
    val out = ByteArray(length)
    val copy = raw.size - start
    System.arraycopy(raw, start, out, length - copy, copy)
    return out
  }

  private fun base64url(bytes: ByteArray): String =
    Base64.encodeToString(bytes, Base64.URL_SAFE or Base64.NO_PADDING or Base64.NO_WRAP)

  // ── DER → raw r||s ────────────────────────────────────────────

  /** `SEQUENCE { INTEGER r, INTEGER s }` → 64 bytes, each left-padded to 32. */
  internal fun derToRaw(der: ByteArray): ByteArray {
    var index = 0

    fun read(): Int {
      if (index >= der.size) throw DeviceKeySignatureFormatException()
      return der[index++].toInt() and 0xff
    }

    fun readLength(): Int {
      val first = read()
      if (first and 0x80 == 0) return first
      val count = first and 0x7f
      if (count == 0 || count > 2) throw DeviceKeySignatureFormatException()
      var length = 0
      repeat(count) { length = (length shl 8) or read() }
      return length
    }

    fun readInteger(): ByteArray {
      if (read() != 0x02) throw DeviceKeySignatureFormatException()
      val length = readLength()
      if (length <= 0 || index + length > der.size) throw DeviceKeySignatureFormatException()
      var start = index
      var end = index + length
      index = end
      // Strip the leading 0x00 DER adds when the top bit is set.
      while (end - start > 32 && der[start].toInt() == 0) start++
      if (end - start > 32) throw DeviceKeySignatureFormatException()
      val out = ByteArray(32)
      System.arraycopy(der, start, out, 32 - (end - start), end - start)
      return out
    }

    if (read() != 0x30) throw DeviceKeySignatureFormatException()
    readLength()
    val r = readInteger()
    val s = readInteger()
    return r + s
  }
}
