// ────────────────────────────────────────────────────────────────
// One process-lifetime secret, generated by main/index.ts when the native
// browser flag is on. Used to authenticate the desktop→server handshake
// route (`POST /internal/browser/cdp-endpoint`) that pushes each workspace's
// current scoped CDP endpoint into the embedded server — NOT used to
// authenticate CDP itself (each ScopedCdpProxy has its own random token).
// ────────────────────────────────────────────────────────────────

let token: string | null = null;

export function setIpcToken(value: string | null): void {
  token = value;
}

export function getIpcToken(): string | null {
  return token;
}
