// ────────────────────────────────────────────────────────────────
// ChatMessage — Domain value object
// ────────────────────────────────────────────────────────────────

import type {
  AgentMode,
  PermissionCardSummary,
  PlanCardSummary,
  QuestionCardSummary,
} from './AgentMode.js';
import type { FileOpStat } from './AgentEvent.js';

export interface ChatMessageMetadata {
  /** Thinking/reasoning text from the harness */
  thinkingText?: string;
  /** Tool calls made during this response */
  toolCalls?: Array<{
    id: string;
    tool: string;
    args: unknown;
    result?: unknown;
    status: 'running' | 'complete';
    /** See {@link PlanCardSummary.sequence}. */
    sequence?: number;
    /** Per-op +/− line stats for file write/edit tools. */
    fileOp?: FileOpStat;
    /** callId of the Agent tool call this ran inside (SDK subagent). */
    parentId?: string;
    /** False when the provider reported the call as failed. */
    success?: boolean;
  }>;
  /** System messages emitted during this response */
  systemMessages?: string[];
  /**
   * Every assistant text segment of the turn, in order.
   *
   * An agentic turn emits many `message_complete` events interleaved with tool
   * calls ("planning…" → 3 tools → "wave 1 running…" → tool → …). `content`
   * holds only the final one, so without this the transcript replays as a wall
   * of tool calls followed by the closing summary — nothing like what streamed.
   * Shares the turn ordinal with `toolCalls[].sequence` and the card summaries.
   */
  textSegments?: Array<{ content: string; sequence?: number }>;
  /** Stage run that produced this message (for per-stage isolation in single-session mode) */
  stageRunId?: string;
  /** Whether this user message is the summary prompt sent at end of a stage */
  isSummaryPrompt?: boolean;
  /** Whether this user message is a predecessor context message injected before stage prompts */
  isContextMessage?: boolean;
  /** Whether this user message carries validation feedback for a retry */
  isValidationFeedback?: boolean;
  /** Whether this user message is a hook-injected context message */
  isHookContext?: boolean;
  /** Whether this assistant message was produced by an in-session validation retry */
  isValidationRetry?: boolean;
  /** Whether this user message is a HITL follow-up prompt the operator sent while
   *  the stage was awaiting input (treated as the HITL response). */
  isFollowUpPrompt?: boolean;
  /** Whether this user message is reviewer feedback captured through the
   *  stage-completion approval flow (a subtype of follow-up prompt). */
  isApprovalFeedback?: boolean;
  /** Which review round produced this feedback (1 = first review). */
  reviewRound?: number;
  /** Whether this assistant message is the response to a HITL follow-up prompt */
  isFollowUpResponse?: boolean;
  /** Whether this user message is an output format enforcement retry */
  isOutputRetry?: boolean;
  /** Whether this assistant message was partially produced before a pause/abort */
  partial?: boolean;
  /** Server-generated stable turn identifier.
   *  Stamped on both the user and assistant message that form a single
   *  chat turn. Enables collision-free dedup on the web client (WEB-02) —
   *  replaces content-based matching which double-counts when identical
   *  text is sent twice. */
  turnId?: string;
  /**
   * The provider-side coordinate of this assistant turn: the Claude message
   * uuid or the Codex turn id the turn ended on. It is what a conversation
   * fork or rewind is expressed in (`forkSession.upToMessageId`,
   * `thread/fork.lastTurnId`, `thread/revert.beforeTurnId`). Absent for
   * providers with no native branching (Copilot) and for turns recorded before
   * anchors were captured — those fall back to the synthetic rewind.
   */
  providerAnchor?: { kind: 'message' | 'turn'; id: string };
  /** Widget instance IDs rendered as part of this message.
   *  The client uses these to reconstitute inline widget blocks on
   *  history replay (see chatMessageToBlocks). */
  widgetInstanceIds?: string[];
  /** Origin of a user-role message when it was NOT typed by the human:
   *  'widget' = generated by a widget via WidgetHostAPI.sendChatMessage.
   *  'system' = generated by an internal control-plane path (e.g. HITL). */
  origin?: 'user' | 'widget' | 'system';
  /** Which agent mode produced this turn. Stamped on both the user and the
   *  assistant message so the transcript can badge plan turns after reload. */
  agentMode?: AgentMode;
  /** Plan documents surfaced during this turn. Persisted so the transcript can
   *  rebuild plan cards from the message alone — event replay is skipped for
   *  completed chats (see apps/web/src/utils/replayEvents.ts). */
  planCards?: PlanCardSummary[];
  /** Clarifying-question cards surfaced during this turn, with their answers. */
  questionCards?: QuestionCardSummary[];
  /** Tool-permission prompts raised during this turn, with the user's decision. */
  permissionCards?: PermissionCardSummary[];
}

export interface ChatMessage {
  id: string;
  sessionId: string;
  /** v2: FK to the Chat entity this message belongs to */
  chatId?: string;
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string;
  attachments?: Array<{
    name: string;
    path: string;
    mimeType: string;
    /** Artifact id when the file is stored as a chat artifact — lets clients
     *  fetch it back (`GET /chats/:id/attachments/:artifactId`). */
    artifactId?: string;
  }>;
  toolName?: string;
  toolArgs?: unknown;
  toolResult?: unknown;
  workflowId?: string;
  /** Rich metadata for assistant messages (thinking, tool calls, system msgs) */
  metadata?: ChatMessageMetadata;
  timestamp: Date;
}
