#!/usr/bin/env tsx
/**
 * Fresh-DB baseline generator (workflow overhaul P00 WP-0.6b, RV-2/RV-3).
 *
 * Runs EVERY migration on an empty database through the historic path
 * (legacy bootstrap + versioned migrations v1..head) and dumps the resulting
 * `sqlite_master` DDL in dependency order: tables (parents before the tables
 * whose REFERENCES point at them, ties in creation order), then indexes,
 * triggers and views. The output is:
 *
 *   packages/db/src/migrations/baseline.sql            — the reviewed artifact
 *   packages/db/src/migrations/baseline.generated.ts   — the same SQL as a
 *     string constant plus BASELINE_VERSION, which `migrateDB` applies to an
 *     empty database (a file read would not survive the desktop server bundle)
 *
 * BASELINE_VERSION is the head migration version. Every migration WP runs
 * this after adding its migration (`pnpm db:baseline`); `--check` fails when
 * the committed files differ from a fresh generation (CI / tests).
 *
 * An empty database must stay empty of rows: a migration that seeds data
 * would need that data in the baseline, so the generator refuses instead of
 * silently producing a baseline without it.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type Database from 'better-sqlite3';
import { closeDB, createDB, migrateDB } from '../packages/db/src/index.js';
import { MIGRATIONS } from '../packages/db/src/migrations/index.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = resolve(HERE, '..', 'packages', 'db', 'src', 'migrations');
const SQL_FILE = resolve(MIGRATIONS_DIR, 'baseline.sql');
const TS_FILE = resolve(MIGRATIONS_DIR, 'baseline.generated.ts');

interface MasterRow {
  type: 'table' | 'index' | 'trigger' | 'view';
  name: string;
  tbl_name: string;
  sql: string | null;
}

/** Tables in dependency order: every REFERENCES target before its dependants. */
function orderTables(tables: MasterRow[]): MasterRow[] {
  const byName = new Map(tables.map((t) => [t.name, t]));
  const out: MasterRow[] = [];
  const state = new Map<string, 'visiting' | 'done'>();
  const visit = (t: MasterRow) => {
    const s = state.get(t.name);
    if (s === 'done') return;
    if (s === 'visiting') return; // self/cyclic reference: creation order decides
    state.set(t.name, 'visiting');
    for (const m of (t.sql ?? '').matchAll(/REFERENCES\s+["`]?(\w+)["`]?/gi)) {
      const parent = byName.get(m[1]!);
      if (parent && parent !== t) visit(parent);
    }
    state.set(t.name, 'done');
    out.push(t);
  };
  for (const t of tables) visit(t);
  return out;
}

/** The DDL a full historic migration produces, in replayable order. */
export function dumpSchema(sqlite: Database.Database): string[] {
  const rows = sqlite
    .prepare(
      `SELECT type, name, tbl_name, sql FROM sqlite_master
        WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'
        ORDER BY rowid`,
    )
    .all() as MasterRow[];
  // A virtual table (FTS5 etc.) creates its own shadow tables (`<vt>_data`,
  // `<vt>_idx`, …) when its CREATE VIRTUAL TABLE runs; replaying them as
  // well would fail with "table already exists".
  const virtual = rows.filter((r) => r.type === 'table' && /^CREATE\s+VIRTUAL\s+TABLE/i.test(r.sql ?? '')).map((r) => r.name);
  const isShadow = (r: MasterRow) => virtual.some((v) => r.tbl_name.startsWith(`${v}_`));
  const tables = orderTables(rows.filter((r) => r.type === 'table' && !isShadow(r)));
  const rest = ['index', 'trigger', 'view'].flatMap((type) => rows.filter((r) => r.type === type && !isShadow(r)));
  // Line endings normalised: the DDL text comes from template literals, which
  // are CRLF on a Windows checkout and LF everywhere else.
  return [...tables, ...rest].map((r) => `${r.sql!.replace(/\r\n/g, '\n').trim()};`);
}

export function generate(): { version: number; sql: string; ts: string } {
  const version = Math.max(...MIGRATIONS.map((m) => m.version));
  const head = MIGRATIONS.find((m) => m.version === version)!;
  const db = createDB(':memory:');
  try {
    migrateDB(db, { path: 'legacy' });
    const sqlite = (db as unknown as { session: { client: Database.Database } }).session.client;

    const seeded = (sqlite
      .prepare(`SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND name <> '_schema_versions'`)
      .all() as Array<{ name: string }>)
      .filter((t) => (sqlite.prepare(`SELECT COUNT(*) AS n FROM "${t.name}"`).get() as { n: number }).n > 0)
      .map((t) => t.name);
    if (seeded.length > 0) {
      throw new Error(`migrations seed rows into an empty database (${seeded.join(', ')}); the baseline cannot carry data`);
    }

    const statements = dumpSchema(sqlite);
    const sql =
      `-- GENERATED by scripts/generate-db-baseline.ts — do not edit by hand.\n` +
      `-- Fresh-DB baseline: the schema every migration up to v${version} (${head.name})\n` +
      `-- produces. migrateDB applies it to an EMPTY database and stamps v1..v${version};\n` +
      `-- existing databases keep the historic path. Regenerate with \`pnpm db:baseline\`.\n\n` +
      statements.join('\n\n') +
      '\n';
    const ts =
      `// GENERATED by scripts/generate-db-baseline.ts — do not edit by hand.\n` +
      `// The same SQL as baseline.sql (the reviewed artifact), embedded so it\n` +
      `// survives bundling. Regenerate with \`pnpm db:baseline\`.\n\n` +
      `/** Head migration version the baseline stands for. */\n` +
      `export const BASELINE_VERSION: number = ${version};\n\n` +
      `/** Contents of baseline.sql. */\n` +
      `export const BASELINE_SQL: string = ${JSON.stringify(sql)};\n`;
    return { version, sql, ts };
  } finally {
    closeDB(db);
  }
}

const read = (f: string) => {
  try {
    return readFileSync(f, 'utf8').replace(/\r\n/g, '\n');
  } catch {
    return '';
  }
};

function main(): number {
  const check = process.argv.includes('--check');
  const { version, sql, ts } = generate();
  if (check) {
    const drift = [
      ...(read(SQL_FILE) === sql ? [] : ['baseline.sql']),
      ...(read(TS_FILE) === ts ? [] : ['baseline.generated.ts']),
    ];
    if (drift.length > 0) {
      console.error(`[db-baseline] out of date: ${drift.join(', ')} — run \`pnpm db:baseline\``);
      return 1;
    }
    console.log(`[db-baseline] baseline v${version} is up to date`);
    return 0;
  }
  writeFileSync(SQL_FILE, sql);
  writeFileSync(TS_FILE, ts);
  console.log(`[db-baseline] wrote baseline v${version} (${sql.split('\n\n').length - 1} statements)`);
  return 0;
}

process.exit(main());
