// ────────────────────────────────────────────────────────────────
// ServerManager — owns the lifecycle of the embedded GeneratorAI server.
//
// The server is run as a child process (isolation: a backend crash restarts
// the process rather than killing the app). It is started in production mode
// so the server serves the built web SPA same-origin at `/`, while the API
// lives at `/api`. The renderer therefore loads a single loopback URL and the
// entire web UI works with zero modifications and zero CORS.
//
//   • Unpackaged (dev / `pnpm preview`): run apps/server/src/index.ts via
//     `node --import tsx` using system Node — matches the prebuilt
//     better-sqlite3 ABI and resolves workspace TS directly.
//   • Packaged: run the compiled apps/server/dist/index.js via Electron's
//     bundled Node (ELECTRON_RUN_AS_NODE) with better-sqlite3 rebuilt for
//     Electron's ABI (see packaging notes / `pnpm rebuild`).
// ────────────────────────────────────────────────────────────────

import { app } from 'electron';
import { spawn, type ChildProcess } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import * as http from 'node:http';
import { EventEmitter } from 'node:events';
import { log } from './logger';
import { resolvePaths, ensureDataDirs, fileExists, type ResolvedPaths } from './paths';
import { findFreePort, preferredPort } from './ports';
import { loadSettings } from './config';
import { loadOrCreateSecretKey } from './secret-protection';
import type { ServerStatus, ServerState } from '../shared/ipc';

const HEALTH_TIMEOUT_MS = 60_000;
const HEALTH_POLL_INTERVAL_MS = 400;
const MAX_AUTO_RESTARTS = 5;

export class ServerManager extends EventEmitter {
  private child: ChildProcess | null = null;
  private paths: ResolvedPaths;
  private port: number | null = null;
  /** Dedicated loopback port for the isolated widget-asset origin (:3101
   *  analogue). Acquired via findFreePort alongside the API port so widget
   *  iframes load from a distinct origin even under dynamic port allocation. */
  private widgetPort: number | null = null;
  private state: ServerState = 'idle';
  private restarts = 0;
  private lastError: string | null = null;
  private harness: ServerStatus['harness'] = null;
  private stopping = false;
  private intentionalStop = false;
  /**
   * Handshake secret generated by Electron main (set at boot when
   * `GENERATORAI_DESKTOP_NATIVE_BROWSER=1`). Plumbed into the server
   * subprocess as `GENERATORAI_ELECTRON_IPC_TOKEN` so it can authenticate
   * `POST /internal/browser/cdp-endpoint` pushes from NativeBrowserHost —
   * each workspace's *scoped, per-tab* CDP endpoint, not a single app-wide
   * one. Also flips on `GENERATORAI_DESKTOP_NATIVE_BROWSER` for the server
   * so `ElectronBridgeAdapter.isAvailable()` returns true.
   */
  private electronIpcToken: string | null = null;
  private nativeBrowserEnabled = false;

  /**
   * Which OS backend protected the vault key for the current child process.
   * Surfaced through `getStatus()` so the renderer can show it in Settings
   * without asking the server (which only knows it received *a* key).
   */
  private secretBackend: string | null = null;

  /**
   * Per-launch secret shared with the embedded server, used only to mint a
   * pairing grant for this shell's renderer. Regenerated on every start so a
   * crashed process cannot leave a reusable admin credential behind.
   */
  private desktopAdminToken: string | null = null;

  /** Which OS keystore protected the vault key, or null when unprotected. */
  getSecretBackend(): string | null {
    return this.secretBackend;
  }

  /**
   * Asks the embedded server for a single-use pairing code so the renderer
   * can pair itself. Returns null when the server is not running or the
   * handshake token is unavailable.
   */
  async requestPairingCode(deviceName?: string): Promise<{
    pairingCode: string;
    pairingUrl: string;
    expiresAt: number;
  } | null> {
    if (!this.port || !this.desktopAdminToken) return null;
    const body = JSON.stringify(deviceName ? { deviceName } : {});
    return new Promise((resolve) => {
      const req = http.request(
        {
          host: '127.0.0.1',
          port: this.port!,
          path: '/internal/desktop/pairing',
          method: 'POST',
          timeout: 5000,
          headers: {
            'content-type': 'application/json',
            'content-length': Buffer.byteLength(body),
            authorization: `Bearer ${this.desktopAdminToken}`,
          },
        },
        (res) => {
          let raw = '';
          res.setEncoding('utf8');
          res.on('data', (c) => (raw += c));
          res.on('end', () => {
            if (res.statusCode !== 201) {
              // Never log `raw` — a success body carries pairing material.
              log.warn('Desktop pairing request failed', { status: res.statusCode });
              return resolve(null);
            }
            try {
              resolve(JSON.parse(raw) as { pairingCode: string; pairingUrl: string; expiresAt: number });
            } catch {
              resolve(null);
            }
          });
        },
      );
      req.on('timeout', () => req.destroy());
      req.on('error', () => resolve(null));
      req.end(body);
    });
  }

  constructor() {
    super();
    this.paths = resolvePaths();
  }

  /** Setter used by main/index.ts once the handshake token is generated. */
  setElectronIpcToken(token: string | null): void {
    this.electronIpcToken = token;
    // The caller only supplies a token when the native browser is on; the
    // token itself is now shared with computer use and minted regardless.
    this.nativeBrowserEnabled = token !== null;
  }

  /** Exposed so the desktop shell can authenticate its own loopback pushes. */
  get ipcToken(): string | null {
    return this.electronIpcToken;
  }

  get url(): string | null {
    return this.port ? `http://127.0.0.1:${this.port}` : null;
  }

  getStatus(): ServerStatus {
    return {
      state: this.state,
      url: this.url,
      port: this.port,
      pid: this.child?.pid ?? null,
      healthy: this.state === 'ready',
      harness: this.harness,
      lastError: this.lastError,
      restarts: this.restarts,
    };
  }

  private setState(state: ServerState, error?: string): void {
    this.state = state;
    if (error !== undefined) this.lastError = error;
    this.emit('status', this.getStatus());
  }

  /** Start the server and resolve once `/api/health` reports ready. */
  async start(): Promise<void> {
    if (this.child) return;
    this.intentionalStop = false;
    this.setState('starting');

    const settings = loadSettings();
    // A restart reuses the previous port when no fixed port is configured, so
    // the window's URL stays valid; `findFreePort` still falls back to a
    // random one if something grabbed it meanwhile — index.ts then repoints
    // the window from the `status` event.
    this.port = await findFreePort(preferredPort(settings.serverPort, this.port));
    // Acquire a separate free port for the isolated widget-asset origin.
    this.widgetPort = await findFreePort(0);
    ensureDataDirs(this.paths);

    const { command, args, cwd } = this.resolveLaunch();
    const env = this.buildEnv();

    log.info('Starting embedded server', { command, args, port: this.port, cwd });

    const child = spawn(command, args, {
      cwd,
      env,
      // The 'ipc' channel exists solely so the server can be asked to shut down
      // gracefully on Windows. Node maps `kill('SIGTERM')` to TerminateProcess
      // there, so a signal can never reach the server's handler; an IPC message
      // can. Without it the desktop — our primary distribution — was the one
      // place the server's teardown and child reaping never ran.
      stdio: ['ignore', 'pipe', 'pipe', 'ipc'],
      windowsHide: true,
    });
    this.child = child;

    child.stdout?.on('data', (b: Buffer) => this.pipeServerLog('info', b));
    child.stderr?.on('data', (b: Buffer) => this.pipeServerLog('warn', b));

    child.on('error', (err) => {
      log.error('Server process error', err);
      this.lastError = err.message;
    });

    child.on('exit', (code, signal) => {
      log.warn('Server process exited', { code, signal });
      this.child = null;
      this.port = this.port; // keep last port for status display
      if (this.intentionalStop || this.stopping) {
        this.setState('stopped');
        return;
      }
      // Unexpected exit → attempt bounded auto-restart.
      this.setState('crashed', `Server exited (code=${code ?? 'null'}, signal=${signal ?? 'null'})`);
      if (this.restarts < MAX_AUTO_RESTARTS) {
        this.restarts += 1;
        const delay = Math.min(1000 * 2 ** (this.restarts - 1), 8000);
        log.info(`Restarting server in ${delay}ms (attempt ${this.restarts})`);
        setTimeout(() => {
          void this.start().catch((e) => log.error('Auto-restart failed', e));
        }, delay);
      } else {
        log.error('Server exceeded max auto-restarts; giving up');
      }
    });

    await this.waitForHealth();
  }

  /** Restart the server (used after settings changes or from the UI). */
  async restart(): Promise<void> {
    this.setState('restarting');
    await this.stop();
    this.restarts = 0;
    await this.start();
  }

  /** Gracefully stop the server, waiting for it to drain. */
  async stop(timeoutMs = 15_000): Promise<void> {
    const child = this.child;
    if (!child) return;
    this.intentionalStop = true;
    this.stopping = true;
    log.info('Stopping embedded server', { pid: child.pid });

    await new Promise<void>((resolve) => {
      let settled = false;
      const done = () => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        resolve();
      };
      const timer = setTimeout(() => {
        log.warn('Server did not exit in time; forcing kill');
        try {
          if (process.platform === 'win32' && child.pid) {
            spawn('taskkill', ['/pid', String(child.pid), '/t', '/f'], { windowsHide: true });
          } else {
            child.kill('SIGKILL');
          }
        } catch {
          /* ignore */
        }
        done();
      }, timeoutMs);

      child.once('exit', done);
      try {
        // Ask first, force later. The server's own shutdown closes the database,
        // flushes queued events and terminates the agent CLIs it spawned; if we
        // go straight to `taskkill /t` none of that happens and the CLIs are
        // left for the next boot's reaper to find.
        //
        // On Windows this MUST be the IPC message: Node maps SIGTERM to
        // TerminateProcess, so the graceful handler would never run. POSIX
        // keeps the signal, which the server already handles.
        let asked = false;
        if (child.connected) {
          asked = child.send({ type: 'shutdown' });
        }
        if (!asked) {
          if (process.platform === 'win32' && child.pid) {
            // No channel to ask over. `taskkill /t` reaps the whole tree, which
            // at least stops the agent subprocesses from holding the inherited
            // stdio pipes open and blocking our own exit.
            spawn('taskkill', ['/pid', String(child.pid), '/t', '/f'], { windowsHide: true });
          } else {
            child.kill('SIGTERM');
          }
        }
      } catch {
        done();
      }
    });

    this.child = null;
    this.stopping = false;
    this.setState('stopped');
  }

  // ── internals ──────────────────────────────────────────────────────────

  private resolveLaunch(): { command: string; args: string[]; cwd: string } {
    const explicitNode = process.env['GENERATORAI_DESKTOP_NODE'];
    if (this.paths.packaged) {
      // Run the compiled server with Electron's bundled Node.
      return {
        command: explicitNode || process.execPath,
        args: [this.paths.serverEntry],
        cwd: this.paths.resourcesDir,
      };
    }
    // Unpackaged: run the TS source via tsx using system Node.
    if (!fileExists(this.paths.serverSrcEntry)) {
      throw new Error(`Server source not found at ${this.paths.serverSrcEntry}`);
    }
    return {
      command: explicitNode || 'node',
      args: ['--import', 'tsx', this.paths.serverSrcEntry],
      cwd: this.paths.repoRoot,
    };
  }

  private buildEnv(): NodeJS.ProcessEnv {
    const settings = loadSettings();
    const port = String(this.port);
    const apiOrigins = [`http://127.0.0.1:${this.port}`, `http://localhost:${this.port}`];
    // The isolated widget-asset origin must (a) serve widgets on its own port,
    // (b) be allowed to fetch the API cross-origin (CORS), and (c) have the
    // widget CSP connect-src point at the ACTUAL dynamic API port — not the
    // hardcoded dev default of :3100. Wire all three from the runtime ports.
    const widgetOrigin = `http://127.0.0.1:${this.widgetPort}`;
    const origins = [...apiOrigins, widgetOrigin].join(',');

    const env: NodeJS.ProcessEnv = {
      ...process.env,
      NODE_ENV: 'production',
      PORT: port,
      WIDGET_PORT: String(this.widgetPort),
      WIDGET_ORIGIN: widgetOrigin,
      WIDGET_CONNECT_SRC: apiOrigins.join(' '),
      // Data paths default to the per-user app-data dir, but honour an
      // explicit override from the launch environment so a developer can
      // point the desktop shell at the repo/dev database (e.g. to inspect
      // existing chats/workflows) without a rebuild.
      DB_PATH: process.env['DB_PATH'] ?? this.paths.dbPath,
      WORKSPACES_DIR: process.env['WORKSPACES_DIR'] ?? this.paths.workspacesDir,
      ARTIFACTS_DIR: process.env['ARTIFACTS_DIR'] ?? this.paths.artifactsDir,
      TEMPLATES_DIR: this.paths.templatesDir,
      // Deterministic web-dist resolution regardless of packaged layout.
      WEB_DIST_DIR: this.paths.webDist,
      CORS_ORIGINS: origins,
      HARNESS_TYPE: settings.harnessType,
      // Quieter logs from the embedded server by default.
      LOG_LEVEL: process.env['GENERATORAI_LOG_LEVEL'] ?? 'info',
    };

    // ── Never inherit the dev "no authentication" override ─────────
    //
    // The shell runs the server with NODE_ENV=production, and the security
    // gate refuses to start a production server with authentication disabled
    // — correctly. But that override is commonly left set in a developer's
    // shell or `apps/server/.env`, which made the desktop app impossible to
    // launch on an otherwise normal dev machine (the server exited 2 in a
    // restart loop and the user saw only "server failed to start").
    //
    // Set to empty rather than deleted: the server's `.env` loader only skips
    // a key that is ALREADY PRESENT in the environment, so deleting it here
    // would let `apps/server/.env` put it straight back.
    //
    // Neutralising it is safe AND correct: the desktop renderer always enrols
    // itself as a properly scoped device over the loopback handshake, so it
    // never needed the override in the first place.
    env['GENERATORAI_ALLOW_UNAUTHENTICATED_LOOPBACK'] = '';

    // ── Vault key ──────────────────────────────────────────────────
    // The server process cannot call Electron's `safeStorage`, so the shell
    // unlocks the OS-protected key encryption key here and passes it down.
    // It lives only in the child's environment, never on disk in plaintext.
    if (!process.env['GENERATORAI_SECRET_KEY'] && !process.env['GENERATORAI_SECRET_PASSPHRASE']) {
      const protection = loadOrCreateSecretKey();
      if (protection) {
        env['GENERATORAI_SECRET_KEY'] = protection.key;
        this.secretBackend = protection.backend;
      } else {
        // The platform could not protect a key (e.g. Linux without a secret
        // service). The server still starts and reports an insecure backend
        // in its posture, so the user is told rather than silently exposed.
        this.secretBackend = 'unprotected';
        log.warn(
          'Starting without an OS-protected vault key. Credentials will be protected only ' +
            'by file permissions. Install gnome-keyring/kwallet, or set GENERATORAI_SECRET_KEY.',
        );
      }
    } else {
      this.secretBackend = 'env';
    }

    // ── Desktop shell handshake ────────────────────────────────────
    // Rotated on every launch and never persisted. Lets the shell mint a
    // pairing grant for its own renderer over loopback (see
    // routes/internal-desktop.ts) without holding a standing admin credential.
    this.desktopAdminToken = randomUUID();
    env['GENERATORAI_DESKTOP_ADMIN_TOKEN'] = this.desktopAdminToken;

    // Plumb the handshake token through so the server can authenticate
    // loopback pushes from Electron main — per-workspace CDP endpoints
    // (routes/internal-browser.ts) and the computer-use driver socket +
    // consent answers (routes/internal-computer.ts).
    //
    // Minted unconditionally: it used to be set only when the native-browser
    // flag produced a token, which silently 401'd every computer-use
    // handshake whenever that flag was off.
    this.electronIpcToken ??= randomUUID();
    env['GENERATORAI_ELECTRON_IPC_TOKEN'] = this.electronIpcToken;
    if (this.nativeBrowserEnabled) {
      env['GENERATORAI_DESKTOP_NATIVE_BROWSER'] = '1';
    }

    if (this.paths.packaged && !process.env['GENERATORAI_DESKTOP_NODE']) {
      env['ELECTRON_RUN_AS_NODE'] = '1';
    }
    return env;
  }

  private pipeServerLog(level: 'info' | 'warn', buf: Buffer): void {
    const text = buf.toString('utf8').trimEnd();
    if (!text) return;
    for (const line of text.split(/\r?\n/)) {
      log[level](`[server] ${line}`);
    }
  }

  private async waitForHealth(): Promise<void> {
    const deadline = Date.now() + HEALTH_TIMEOUT_MS;
    while (Date.now() < deadline) {
      if (!this.child) {
        throw new Error(this.lastError ?? 'Server process exited before becoming healthy');
      }
      const health = await this.probeHealth();
      if (health) {
        this.harness = health.harness
          ? { type: health.harness.type, healthy: health.harness.healthy }
          : null;
        this.restarts = 0;
        this.setState('ready');
        log.info('Embedded server is ready', { url: this.url, harness: this.harness });
        return;
      }
      await delay(HEALTH_POLL_INTERVAL_MS);
    }
    throw new Error(`Server did not become healthy within ${HEALTH_TIMEOUT_MS}ms`);
  }

  private probeHealth(): Promise<HealthResponse | null> {
    return new Promise((resolve) => {
      if (!this.port) return resolve(null);
      const req = http.get(
        { host: '127.0.0.1', port: this.port, path: '/api/health', timeout: 2000 },
        (res) => {
          if (res.statusCode !== 200) {
            res.resume();
            return resolve(null);
          }
          let body = '';
          res.setEncoding('utf8');
          res.on('data', (c) => (body += c));
          res.on('end', () => {
            try {
              resolve(JSON.parse(body) as HealthResponse);
            } catch {
              resolve(null);
            }
          });
        },
      );
      req.on('timeout', () => req.destroy());
      req.on('error', () => resolve(null));
    });
  }
}

interface HealthResponse {
  status: string;
  harness?: { type: string; healthy: boolean };
}

function delay(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

// Keep a module-level reference so the lifecycle code can reach it on quit.
let instance: ServerManager | null = null;
export function getServerManager(): ServerManager {
  if (!instance) instance = new ServerManager();
  return instance;
}

// `will-quit` cannot hold the app open for async work, so the child was being
// orphaned mid-drain. Defer the quit until the server is actually down.
let quitCleanupStarted = false;
app.on('before-quit', (event) => {
  if (quitCleanupStarted || !instance) return;
  quitCleanupStarted = true;
  event.preventDefault();
  void instance
    .stop()
    .catch(() => undefined)
    .finally(() => app.quit());
});
