'use strict';

// ────────────────────────────────────────────────────────────────
// withSceneLifecycle — adopt the UIScene life cycle on iOS.
//
// From iOS 27 UIKit refuses to launch an app that has not adopted scenes:
// the process starts, logs "Application failed to launch: UIScene life cycle
// is required" and exits with SIGTRAP before a single frame is drawn. The
// Expo SDK 57 / React Native 0.86 template still creates its window in
// `application(_:didFinishLaunchingWithOptions:)` (the pre-iOS 13 model), so
// every build from that template dies on launch on iOS 27.
//
// This plugin moves window creation into a UIWindowSceneDelegate and keeps
// everything the old path provided:
//   • Info.plist gets a single-scene `UIApplicationSceneManifest`;
//   • AppDelegate keeps building the React Native factory but only records
//     the launch options — the scene delegate creates the window and starts
//     React Native in it;
//   • a cold-start deep link or universal link (a pairing link, a
//     notification's route) arrives in the scene's connection options, not
//     in launch options, so it is folded back into the launch options React
//     Native reads for `Linking.getInitialURL()`;
//   • later links and the foreground/background transitions are forwarded to
//     the AppDelegate / Expo subscriber paths that Expo modules (linking,
//     notifications, local authentication…) already listen to, since UIKit
//     stops calling those app-delegate methods once scenes are adopted.
//
// Pure transforms are exported for tests; the plugin fails prebuild loudly if
// the template changes shape rather than silently shipping an app that cannot
// launch.
// ────────────────────────────────────────────────────────────────

const fs = require('fs');
const path = require('path');
const { withAppDelegate, withInfoPlist, withXcodeProject, IOSConfig } = require('expo/config-plugins');

const MARKER = '// GeneratorAI: UIScene life cycle';
const SCENE_FILE = 'SceneDelegate.swift';
const CONFIGURATION_NAME = 'Default Configuration';

function sceneManifest() {
  return {
    UIApplicationSupportsMultipleScenes: false,
    UISceneConfigurations: {
      UIWindowSceneSessionRoleApplication: [
        {
          UISceneConfigurationName: CONFIGURATION_NAME,
          UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
        },
      ],
    },
  };
}

const WINDOW_BLOCK = /#if os\(iOS\) \|\| os\(tvOS\)\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\n\s*factory\.startReactNative\(\n\s*withModuleName: "main",\n\s*in: window,\n\s*launchOptions: launchOptions\)\n#endif\n/;
const FACTORY_PROPERTY = '  var reactNativeFactory: RCTReactNativeFactory?\n';

function applySceneAppDelegate(source) {
  if (source.includes(MARKER)) return source;
  if (!WINDOW_BLOCK.test(source)) {
    throw new Error('withSceneLifecycle: the AppDelegate no longer creates its window the way the Expo template did; update the plugin.');
  }
  if (!source.includes(FACTORY_PROPERTY)) {
    throw new Error('withSceneLifecycle: AppDelegate has no `reactNativeFactory` property; update the plugin.');
  }
  return source
    .replace(
      FACTORY_PROPERTY,
      `${FACTORY_PROPERTY}  ${MARKER}: kept for SceneDelegate, which starts React Native.\n  var launchOptions: [UIApplication.LaunchOptionsKey: Any]?\n`,
    )
    .replace(
      WINDOW_BLOCK,
      `    ${MARKER}: the window and React Native start in SceneDelegate.\n    self.launchOptions = launchOptions\n`,
    )
    .replace(
      /\n}\n\nclass ReactNativeDelegate/,
      `

  ${MARKER}: one window scene, driven by SceneDelegate.
  // Not an override: ExpoAppDelegate does not implement it. \`@objc\` so UIKit
  // finds it through the delegate's inherited UIApplicationDelegate conformance.
  @objc public func application(
    _ application: UIApplication,
    configurationForConnecting connectingSceneSession: UISceneSession,
    options: UIScene.ConnectionOptions
  ) -> UISceneConfiguration {
    let configuration = UISceneConfiguration(name: "${CONFIGURATION_NAME}", sessionRole: connectingSceneSession.role)
    configuration.delegateClass = SceneDelegate.self
    return configuration
  }
}

class ReactNativeDelegate`,
    );
}

function sceneDelegateSource() {
  return `internal import Expo
import React
import UIKit

${MARKER}.
// Generated by plugins/withSceneLifecycle.js — edit the plugin, not this file.
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  private var appDelegate: AppDelegate? {
    UIApplication.shared.delegate as? AppDelegate
  }

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene,
          let appDelegate = appDelegate,
          let factory = appDelegate.reactNativeFactory else { return }

    // A cold-start link arrives here rather than in launch options; put it
    // where React Native looks for the initial URL.
    var launchOptions = appDelegate.launchOptions ?? [:]
    if let url = connectionOptions.urlContexts.first?.url {
      launchOptions[.url] = url
    }
    if let activity = connectionOptions.userActivities.first {
      launchOptions[.userActivityDictionary] = [
        "UIApplicationLaunchOptionsUserActivityTypeKey": activity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": activity,
      ]
    }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    appDelegate.window = window
    factory.startReactNative(withModuleName: "main", in: window, launchOptions: launchOptions)
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    guard let appDelegate = appDelegate else { return }
    for context in URLContexts {
      var options: [UIApplication.OpenURLOptionsKey: Any] = [:]
      if let source = context.options.sourceApplication { options[.sourceApplication] = source }
      _ = appDelegate.application(UIApplication.shared, open: context.url, options: options)
    }
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    _ = appDelegate?.application(UIApplication.shared, continue: userActivity, restorationHandler: { _ in })
  }

  // UIKit stops calling the app-delegate versions of these once scenes are
  // adopted; Expo modules still subscribe to them.
  func sceneDidBecomeActive(_ scene: UIScene) {
    ExpoAppDelegateSubscriberManager.applicationDidBecomeActive(UIApplication.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    ExpoAppDelegateSubscriberManager.applicationWillResignActive(UIApplication.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    ExpoAppDelegateSubscriberManager.applicationDidEnterBackground(UIApplication.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    ExpoAppDelegateSubscriberManager.applicationWillEnterForeground(UIApplication.shared)
  }
}
`;
}

function withSceneLifecycle(config) {
  config = withInfoPlist(config, (mod) => {
    mod.modResults.UIApplicationSceneManifest = sceneManifest();
    return mod;
  });

  config = withAppDelegate(config, (mod) => {
    if (mod.modResults.language !== 'swift') throw new Error('withSceneLifecycle requires a Swift AppDelegate.');
    mod.modResults.contents = applySceneAppDelegate(mod.modResults.contents);
    return mod;
  });

  config = withXcodeProject(config, (mod) => {
    const projectName = IOSConfig.XcodeUtils.getProjectName(mod.modRequest.projectRoot);
    const target = path.join(mod.modRequest.platformProjectRoot, projectName, SCENE_FILE);
    fs.writeFileSync(target, sceneDelegateSource());
    const groupPath = projectName;
    const relative = `${projectName}/${SCENE_FILE}`;
    if (!mod.modResults.hasFile(relative)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath: relative,
        groupName: groupPath,
        project: mod.modResults,
      });
    }
    return mod;
  });

  return config;
}

module.exports = withSceneLifecycle;
module.exports.applySceneAppDelegate = applySceneAppDelegate;
module.exports.sceneDelegateSource = sceneDelegateSource;
module.exports.sceneManifest = sceneManifest;
